In [2]:
import os
import numpy as np
import scipy.sparse as sp

from quant_rotor.CCC_iterative_methods.Dense.t_amplitudes_periodic import t_periodic

# Dense (Slow)
from quant_rotor.Hamiltonian_models.Dense.rotor_hamiltonian import hamiltonian_dense
from quant_rotor.Hamiltonian_models.Dense.hamiltonian_big import hamiltonian_general_dense

# Sparse (Fast)
from quant_rotor.Hamiltonian_models.Sparse.hamiltonian import hamiltonian_sparse
from quant_rotor.Hamiltonian_models.Sparse.hamiltonian_big import hamiltonian_general_sparse

from quant_rotor.Hamiltonian_models.Dense.support_ham import (
    H_kinetic,
    V_double,
    basis_m_to_p_matrix_conversion,
    write_matrix_elements,
)

from quant_rotor.Hamiltonian_models.Sparse.support_ham import (build_V_in_p)

ImportError: cannot import name 'H_potential' from 'quant_rotor.Hamiltonian_models.Dense.support_ham' (/Users/gilfrim/Desktop/Projects/Computational_Analysis_of_Many_Rotor_Systems/quant_rotor/Hamiltonian_models/Dense/support_ham.py)

In [6]:
np.set_printoptions(precision=5)
np.set_printoptions(suppress=True)
np.set_printoptions(linewidth=np.inf)
np.set_printoptions(threshold=np.inf)

In [ ]:
H_bryan = np.array([[ 0,   0,   0,   0,   7.5, -2.5,  0,  -2.5,  7.5,  0,   7.5, -2.5,  7.5,  0,   0,  -2.5,  0,   0,   0,  -2.5,  7.5, -2.5,  0,   0,   7.5,  0,   0, ],
[ 0,   1,   0,  -2.5,  0,   0,   7.5,  0,   0,  -2.5,  0,   0,   0,   7.5,  0,   0,  -2.5,  0,   7.5,  0,   0,   0,  -2.5,  0,   0,   7.5,  0, ],
 [ 0,   0,   1,   7.5,  0,   0,  -2.5,  0,   0,   7.5,  0,   0,   0,   0,   7.5,  0,   0,  -2.5, -2.5,  0,   0,   0,   0,  -2.5,  0,   0,   7.5,],
 [ 0,  -2.5,  7.5,  1,   0,   0,   0,   0,   0,  -2.5,  0,   0,   0,   7.5, -2.5,  0,   0,   0,   7.5,  0,   0,   0,  -2.5,  7.5,  0,   0,   0, ],
 [ 7.5,  0,   0,   0,   2,  0,   0,   0,   0,   0,  -2.5,  0,  -2.5,  0,   0,   0,   0,   0,   0,   7.5,  0,   7.5,  0,   0,   0,   0,   0, ],
 [-2.5,  0,   0,   0,   0,   2,  0,   0,   0,   0,   0,  -2.5,  7.5,  0,   0,   0,   0,   0,   0,   0,   7.5, -2.5,  0,   0,   0,   0,   0, ],
 [ 0,   7.5, -2.5,  0,   0,   0,   1,   0,   0,   7.5,  0,   0,   0,   0,   0,   0,   7.5, -2.5, -2.5,  0,   0,   0,   0,   0,   0,  -2.5,  7.5,],
 [-2.5,  0,   0,   0,   0,   0,   0,   2,  0,   0,   7.5,  0,   0,   0,   0,  -2.5,  0,   0,   0,  -2.5,  0,   0,   0,   0,   7.5,  0,   0, ],
 [ 7.5,  0,   0,   0,   0,   0,   0,   0,   2,  0,   0,   7.5,  0,   0,   0,   7.5,  0,   0,   0,   0,  -2.5,  0,   0,   0,  -2.5,  0,   0, ],
 [ 0,  -2.5,  7.5, -2.5,  0,   0,   7.5,  0,   0,   1,   0,   0,   0,   7.5, -2.5,  0,  -2.5,  7.5,  0,   0,   0,   0,   0,   0,   0,   0,   0, ],
 [ 7.5,  0,   0,   0,  -2.5,  0,   0,   7.5,  0,   0,   2,  0,  -2.5,  0,   0,   7.5,  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0, ],
 [-2.5,  0,   0,   0,   0,  -2.5,  0,   0,   7.5,  0,   0,   2,  7.5,  0,   0,  -2.5,  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0, ],
 [ 7.5,  0,   0,   0,  -2.5,  7.5,  0,   0,   0,   0,  -2.5,  7.5,  2,  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0, ],
 [ 0,   7.5,  0,   7.5,  0,   0,   0,   0,   0,   7.5,  0,   0,   0,   3,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0, ],
 [ 0,   0,   7.5, -2.5,  0,   0,   0,   0,   0,  -2.5,  0,   0,   0,   0,   3,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0, ],
 [-2.5,  0,   0,   0,   0,   0,   0,  -2.5,  7.5,  0,   7.5, -2.5,  0,   0,   0,   2,  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0, ],
 [ 0,  -2.5,  0,   0,   0,   0,   7.5,  0,   0,  -2.5,  0,   0,   0,   0,   0,   0,   3,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0, ],
 [ 0,   0,  -2.5,  0,   0,   0,  -2.5,  0,   0,   7.5,  0,   0,   0,   0,   0,   0,   0,   3,   0,   0,   0,   0,   0,   0,   0,   0,   0, ],
 [ 0,   7.5, -2.5,  7.5,  0,   0,  -2.5,  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   1,   0,   0,   0,   7.5, -2.5,  0,  -2.5,  7.5,],
 [-2.5,  0,   0,   0,   7.5,  0,   0,  -2.5,  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   2,  0,  -2.5,  0,   0,   7.5,  0,   0, ],
 [ 7.5,  0,   0,   0,   0,   7.5,  0,   0,  -2.5,  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   2,  7.5,  0,   0,  -2.5,  0,   0, ],
 [-2.5,  0,   0,   0,   7.5, -2.5,  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,  -2.5,  7.5,  2,  0,   0,   0,   0,   0, ],
 [ 0,  -2.5,  0,  -2.5,  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   7.5,  0,   0,   0,   3,   0,   0,   0,   0, ],
 [ 0,   0,  -2.5,  7.5,  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,  -2.5,  0,   0,   0,   0,   3,   0,   0,   0, ],
 [ 7.5,  0,   0,   0,   0,   0,   0,   7.5, -2.5,  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   7.5, -2.5,  0,   0,   0,   2,  0,   0, ],
 [ 0,   7.5,  0,   0,   0,   0,  -2.5,  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,  -2.5,  0,   0,   0,   0,   0,   0,   3,   0, ],
 [ 0,   0,   7.5,  0,   0,   0,   7.5,  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   7.5,  0,   0,   0,   0,   0,   0,   0,   3, ]])

# Setup Parallel Processing

In [6]:
print("Logical cores:", os.cpu_count())

Logical cores: 10


# Access to sites

In [65]:
site = 5

In [66]:
t_2 = np.zeros((site))

In [ ]:
for i in range(1, site):
    t_2[i], = i
print(t_2)

[0. 1. 2. 3. 4.]


In [17]:
t_2_2D = np.zeros((site, site))

In [ ]:
for i in range(1, site+1):
    for j in range(i, site+1):
        t_2_2D[i-1, j-1], = (i * 10) + j

print(t_2_2D)

[[11. 12. 13. 14. 15.]
 [ 0. 22. 23. 24. 25.]
 [ 0.  0. 33. 34. 35.]
 [ 0.  0.  0. 44. 45.]
 [ 0.  0.  0.  0. 55.]]


In [25]:
site = 7

In [ ]:
t_2_3D = np.zeros((site-1, site-1, site-1))

for i in range(1, site):
    for j in range(i, site):
        for k in range(j, site):
            t_2_3D[i-1, j-1, k - 1], = 100 * i + 10 * j + k

print(t_2_3D)

[[[111. 112. 113. 114. 115. 116.]
  [  0. 122. 123. 124. 125. 126.]
  [  0.   0. 133. 134. 135. 136.]
  [  0.   0.   0. 144. 145. 146.]
  [  0.   0.   0.   0. 155. 156.]
  [  0.   0.   0.   0.   0. 166.]]

 [[  0.   0.   0.   0.   0.   0.]
  [  0. 222. 223. 224. 225. 226.]
  [  0.   0. 233. 234. 235. 236.]
  [  0.   0.   0. 244. 245. 246.]
  [  0.   0.   0.   0. 255. 256.]
  [  0.   0.   0.   0.   0. 266.]]

 [[  0.   0.   0.   0.   0.   0.]
  [  0.   0.   0.   0.   0.   0.]
  [  0.   0. 333. 334. 335. 336.]
  [  0.   0.   0. 344. 345. 346.]
  [  0.   0.   0.   0. 355. 356.]
  [  0.   0.   0.   0.   0. 366.]]

 [[  0.   0.   0.   0.   0.   0.]
  [  0.   0.   0.   0.   0.   0.]
  [  0.   0.   0.   0.   0.   0.]
  [  0.   0.   0. 444. 445. 446.]
  [  0.   0.   0.   0. 455. 456.]
  [  0.   0.   0.   0.   0. 466.]]

 [[  0.   0.   0.   0.   0.   0.]
  [  0.   0.   0.   0.   0.   0.]
  [  0.   0.   0.   0.   0.   0.]
  [  0.   0.   0.   0.   0.   0.]
  [  0.   0.   0.   0. 555. 556.]
  [  0

# Building the potential.

In [10]:
site = 3
state = 3

In [11]:
K_op, V_op = write_matrix_elements((state - 1)//2)

In [12]:
K_op = basis_m_to_p_matrix_conversion(K_op, state)
V_op = basis_m_to_p_matrix_conversion(V_op.reshape(state, state, state, state), state)

## 1-D

### Kinetic

In [ ]:
def test_K_1D(states: int, sites: int, K: np.ndarray) -> np.ndarray:

    # Create a matrix of the shape of Kinetic energy Hamiltonian filled with zeros.
    K_H = np.zeros((states**sites, states**sites), dtype=complex)

    counter = 0

    for x in range(sites):

        # Define the total number of elements in the matrix operator, which represent the left and right sites that are not interacting
        # by n_lambda and n_mu respectively.
        n_lambda = states ** (x)
        n_mu = states ** (sites - x - 1)

        print("Old: ", n_lambda, n_mu)

        # Iterate through all elements of the Kinetic energy matrix operator.
        for p in range(states):
            for p_prime in range(states):

                # Extract an associated element.
                val = K[p, p_prime]

                # Check if element is non zero.
                # if val == 0:
                #     continue

                for Lambda in range(int(n_lambda)):
                    for mu in range(int(n_mu)):

                        # Calculate the indices in the hamiltonian.
                        i = mu + p * n_mu + Lambda * n_mu
                        j = mu + p_prime * n_mu + Lambda * states * n_mu

                        counter += 1
    print(counter)


In [ ]:
def H_kinetic_1D(states: int, sites: int, K: np.ndarray) -> np.ndarray:

    K_H = np.zeros((states**sites, states**sites), dtype=complex)

    for x in range(sites):

        n_lambda = states ** (x)
        n_mu = states ** (sites - x - 1)

        for p in range(states):
            for p_prime in range(states):

                val = K[p, p_prime]

                if val == 0:
                    continue

                for Lambda in range(int(n_lambda)):
                    for mu in range(int(n_mu)):

                        i = mu + p * n_mu + Lambda * states * n_mu
                        j = mu + p_prime * n_mu + Lambda * states * n_mu

                        K_H[i, j] += val
    return K_H

In [ ]:
K_1D = H_kinetic_1D(state, site, K_op)
K_old = H_kinetic(state, site, K_op)

In [ ]:
np.array_equal(K_1D, K_old)

True

### Potential

In [ ]:
site_x = 3
site_y = 3

In [ ]:
def test_V(
    states: int, site_x: int, site_y: int, V: np.ndarray, periodic: bool
) -> np.ndarray:

    sites = site_x * site_y

    # Create a matrix of the shape of Potential energy Hamiltonian filled with zeros.
    V_H = np.zeros((states**sites, states**sites), dtype=complex)

    for y in range(site_y):
        for x in range(site_x):

            site_1 = x + 3 * y

            # With x defining the first site of two-body interaction, we define the second dynamically.
            site_2_new = (x + 1) % site_x + site_x * y
            site_2_old = (site_1 + 1) % sites

            n_lambda_x = (site_1 % (sites - 1))
            n_mu_x = ((sites - site_2_new - 1) % (sites - 1))
            n_nu_x = (np.abs(site_2_new - site_1) - 1)

            n_lambda = (site_1 % (sites - 1))
            n_mu = ((sites - site_2_old - 1) % (sites - 1))
            n_nu = (np.abs(site_2_old - site_1) - 1)

            print("Old:", n_lambda, n_nu, n_mu)
            # print("New:", n_lambda_x, n_nu_x, n_mu_x, "\n")

            # print("Site old:", site_1, site_2_old)
            # print("Site new:", site_1, site_2_new, "\n")

In [ ]:
test_V(state, site_x, site_y, V_op.reshape(state**2, state**2), True)

Old: 0 0 7
Old: 1 0 6
Old: 2 0 5
Old: 3 0 4
Old: 4 0 3
Old: 5 0 2
Old: 6 0 1
Old: 7 0 0
Old: 0 7 0


In [ ]:
site = 9

for x in range(site):
    # With x defining the first site of two-body interaction, we define the second dynamically.
    y = (x + 1) % site

    # Define the total number of elements in the matrix operator, which represent the left, right, and center sites that are not interacting
    # by n_lambda, n_mu, n_nu, respectively.
    n_lambda = (x % (site - 1))
    n_mu = ((site - y - 1) % (site - 1))
    n_nu = (np.abs(y - x) - 1)

    print("Old:", n_lambda, n_nu, n_mu)

site = 3

Old: 0 0 7
Old: 1 0 6
Old: 2 0 5
Old: 3 0 4
Old: 4 0 3
Old: 5 0 2
Old: 6 0 1
Old: 7 0 0
Old: 0 7 0


In [ ]:
def H_potential_1D(
    states: int, sites: int, V: np.ndarray, periodic: bool
) -> np.ndarray:

    # Create a matrix of the shape of Potential energy Hamiltonian filled with zeros.
    V_H = np.zeros((states**sites, states**sites), dtype=complex)

    if periodic:
        site_range = sites
    else:
        site_range = sites - 1


    for x in range(site_range):

        # With x defining the first site of two-body interaction, we define the second dynamically.
        y = (x + 1) % sites

        # Define the total number of elements in the matrix operator, which represent the left, right, and center sites that are not interacting
        # by n_lambda, n_mu, n_nu, respectively.
        n_lambda = states ** (x % (sites - 1))
        n_mu = states ** ((sites - y - 1) % (sites - 1))
        n_nu = states ** (np.abs(y - x) - 1)

        # Iterate through all elements of the Potential energy matrix operator.
        for q in range(states):
            for q_prime in range(states):
                for p in range(states):
                    for p_prime in range(states):

                        # Calculate the flattened indices of the associated element.
                        row = p * states + q
                        col = p_prime * states + q_prime
                        val = V[row, col]

                        # Check if element is non zero.
                        if np.allclose(val, 0, atol=1e-25):
                            continue  # skip writing 0s

                        for Lambda in range(int(n_lambda)):
                            for mu in range(int(n_mu)):
                                for nu in range(int(n_nu)):

                                    # Calculate the indices in the hamiltonian.
                                    i = (
                                        mu
                                        + q * n_mu
                                        + nu * states * n_mu
                                        + p * n_nu * n_mu * states
                                        + Lambda * n_nu * n_mu * states**2
                                    )
                                    j = (
                                        mu
                                        + q_prime * n_mu
                                        + nu * states * n_mu
                                        + p_prime * n_nu * n_mu * states
                                        + Lambda * n_nu * n_mu * states**2
                                    )

                                    # Assign a values to associated.
                                    V_H[i, j] = val
    return V_H

In [ ]:
V_1D = H_potential_1D(state, site, V_op.reshape(state**2, state**2), True)

In [ ]:
V_old = H_potential_double(state, site, V_op.reshape(state**2, state**2), 1, True, False)

In [ ]:
np.array_equal(V_1D, V_old)

True

## 2-D

### Kinetic

In [15]:
site_x = 3
site_y = 3

In [16]:
site_index_matrix = np.arange(site_x * site_y).reshape(site_y, site_x)

In [17]:
sites = site_x * site_y

### Potential Horisontal

In [18]:
for y in range(site_y):
    for x in range(site_x):

        tail = site_index_matrix[y, x]
        head = site_index_matrix[y, (x + 1) % (site_x)]

        print(np.minimum(tail, head), np.maximum(tail, head))

0 1
1 2
0 2
3 4
4 5
3 5
6 7
7 8
6 8


In [25]:
site_index_matrix[0]

array([0, 1, 2])

In [31]:
for x in range(site_x - 1):
    for y in range(site_y):
        tail = x + site_x * y
        head = site_x*(y) + ((x + 1) % (site_x))
        print("New:", tail, head)

New: 0 1
New: 3 4
New: 6 7
New: 1 2
New: 4 5
New: 7 8


In [33]:
x = 2
for y in range(site_y):
    tail = x + site_x * y
    head = site_x*(y) + ((x + 1) % (site_x))
    print("New:", tail, head)

New: 2 0
New: 5 3
New: 8 6


In [27]:
for y in range(site_y):
    for x in range(site_x):

        tail_x = site_index_matrix[y, x]
        head_x = site_index_matrix[y, (x + 1) % (site_x)]

        site_tail_x = np.minimum(tail_x, head_x)
        site_head_x = np.maximum(tail_x, head_x)

        tail = x + site_x * y
        head = site_x*(y) + ((x + 1) % (site_x))

        n_lambda_x = (site_tail_x % (sites - 1))
        n_mu_x = (sites - 1 - site_head_x)
        n_nu_x = (np.abs(site_head_x - site_tail_x) - 1)

        print("New:", tail, head)
        print("old:", tail_x, head_x)
        print("\n")

        # print("Labmda - Mu:", n_lambda_x , n_nu_x, n_mu_x)
        # print("Sum:", n_lambda_x + n_nu_x + n_mu_x + 2)

New: 0 1
old: 0 1


New: 1 2
old: 1 2


New: 2 0
old: 2 0


New: 3 4
old: 3 4


New: 4 5
old: 4 5


New: 5 3
old: 5 3


New: 6 7
old: 6 7


New: 7 8
old: 7 8


New: 8 6
old: 8 6




In [44]:
def H_potential_2D_x(
    states: int, site_x: int, site_y: int, V: np.ndarray, periodic: bool
) -> np.ndarray:

    sites = site_x * site_y

    # Create a matrix of the shape of Potential energy Hamiltonian filled with zeros.
    V_H = np.zeros((states**sites, states**sites), dtype=complex)

    if periodic:
        site_range = sites
    else:
        site_range = sites - 1

    for y in range(site_y):
        for x in range(site_x):

            sites = site_x * site_y

            tail_x = site_index_matrix[y, x]
            head_x = site_index_matrix[y, (x + 1) % (site_x)]

            site_tail_x = np.minimum(tail_x, head_x)
            site_head_x = np.maximum(tail_x, head_x)

            n_lambda = state**(site_tail_x % (sites - 1))
            n_mu = state**(sites - 1 - site_head_x)
            n_nu = state**(np.abs(site_head_x - site_tail_x) - 1)

            if states**sites != n_lambda * n_mu * n_nu * states**2:
                raise ValueError("Wrong dimention")

            # Iterate through all elements of the Potential energy matrix operator.
            for q in range(states):
                for q_prime in range(states):
                    for p in range(states):
                        for p_prime in range(states):

                            # Calculate the flattened indices of the associated element.
                            row = p * states + q
                            col = p_prime * states + q_prime
                            val = V[row, col]

                            # Check if element is non zero.
                            if np.allclose(val, 0, atol=1e-25):
                                continue  # skip writing 0s

                            for Lambda in range(int(n_lambda)):
                                for mu in range(int(n_mu)):
                                    for nu in range(int(n_nu)):

                                        # Calculate the indices in the hamiltonian.
                                        i = (
                                            mu
                                            + q * n_mu
                                            + nu * states * n_mu
                                            + p * n_nu * n_mu * states
                                            + Lambda * n_nu * n_mu * states**2
                                        )
                                        j = (
                                            mu
                                            + q_prime * n_mu
                                            + nu * states * n_mu
                                            + p_prime * n_nu * n_mu * states
                                            + Lambda * n_nu * n_mu * states**2
                                        )

                                        # Assign a values to associated.
                                        V_H[i, j] += val
    return V_H

In [45]:
def H_potential_sparse_2D_x(
    state: int, site_x: int, site_y: int, V: np.ndarray, periodic: bool
) -> np.ndarray:

    sites = site_x * site_y

    dim = state**sites
    rows = []
    cols = []
    data = []

    # Use COO for fast iteration
    V = V.tocoo()

    if periodic:
        site_range = site
    else:
        site_range = site - 1

    for y in range(site_y):
        for x in range(site_x):
        # With x defining the first site of two-body interaction, we define the second dynamically.


            tail_x = site_index_matrix[y, x]
            head_x = site_index_matrix[y, (x + 1) % (site_x)]

            site_tail_x = np.minimum(tail_x, head_x)
            site_head_x = np.maximum(tail_x, head_x)

            n_lambda = state**(site_tail_x % (sites - 1))
            n_mu = state**(sites - 1 - site_head_x)
            n_nu = state**(np.abs(site_head_x - site_tail_x) - 1)

            # Define place values for state based numerical system.
            stride_q = n_mu
            stride_nu = state * n_mu
            stride_p = n_nu * n_mu * state
            stride_lambda = n_nu * n_mu * state ** 2

            # Create a new list of row, column and data indecies.
            for row_2s, col_2s, val in zip(
                V.row, V.col, V.data
            ):  # Iterate only through non-zero elements of the
                # Unflatten the indices.
                p, q = divmod(row_2s, state)
                p_prime, q_prime = divmod(col_2s, state)

                for Lambda in range(n_lambda):
                    for mu in range(n_mu):
                        for nu in range(n_nu):
                            # Calculate the indices in the hamiltonian.
                            i = mu + q * stride_q + nu * stride_nu + p * stride_p + Lambda * stride_lambda
                            j = mu + q_prime * stride_q + nu * stride_nu + p_prime * stride_p + Lambda * stride_lambda

                            # Uppend them to a new rows, collumns and data arrays.
                            rows.append(i)
                            cols.append(j)
                            data.append(val)

    rows = np.asarray(rows, dtype=np.float64)
    cols = np.asarray(cols, dtype=np.float64)
    data = np.asarray(data, dtype=np.float64)

    # Return a new sparse array of the potential energy part of the mamiltonian.
    return sp.csr_matrix((data, (rows, cols)), shape=(dim, dim), dtype=np.float64)

In [46]:
K_s, V_s = build_V_in_p(state)

In [47]:
# V_2D_x = H_potential_2D_x(state, site_x, site_y, V_op.reshape(state**2, state**2), True)
V_2D_x = H_potential_sparse_2D_x(state, site_x, site_y, V_s, True)
V_old = H_potential_double(state, site_x, V_op.reshape(state**2, state**2), 1, True, False)

print("Done.")

eig_val_2D_x, eig_vec_2D_x = sp.linalg.eigsh(V_2D_x, k=1, which='SA', tol=1e-19, maxiter=2000)
eig_val_old, eig_vec_old = np.linalg.eigh(V_old)

print(eig_val_2D_x[0] - np.min(eig_val_old) * site_y)

Done.
-5.329070518200751e-15


### Potential Vertical

In [77]:
# site_x = np.minimum(site_x, site_y)
# site_y = np.maximum(site_x, site_y)

for y in range(site_x):
    for x in range(site_y):

        tail = site_index_matrix.T[y, x]
        head = site_index_matrix.T[y, (x + 1) % (site_y)]

        print(tail, head)
        # print(np.minimum(tail, head), np.maximum(tail, head))

0 3
3 6
6 9
9 0
1 4
4 7
7 10
10 1
2 5
5 8
8 11
11 2


In [78]:
for y in range(site_x):
    for x in range(site_y):

        tail_x = site_index_matrix.T[y, x]
        head_x = site_index_matrix.T[y, (x + 1) % (site_y)]

        site_tail_x = np.minimum(tail_x, head_x)
        site_head_x = np.maximum(tail_x, head_x)

        n_lambda_x = (site_tail_x % (sites - 1))
        n_mu_x = (sites - 1 - site_head_x)
        n_nu_x = (np.abs(site_head_x - site_tail_x) - 1)

        # print("New:", site_1_x, site_2_x)

        print("Labmda - Mu:", n_lambda_x , n_nu_x, n_mu_x)
        print("Sum:", n_lambda_x + n_nu_x + n_mu_x + 2)

Labmda - Mu: 0 2 8
Sum: 12
Labmda - Mu: 3 2 5
Sum: 12
Labmda - Mu: 6 2 2
Sum: 12
Labmda - Mu: 0 8 2
Sum: 12
Labmda - Mu: 1 2 7
Sum: 12
Labmda - Mu: 4 2 4
Sum: 12
Labmda - Mu: 7 2 1
Sum: 12
Labmda - Mu: 1 8 1
Sum: 12
Labmda - Mu: 2 2 6
Sum: 12
Labmda - Mu: 5 2 3
Sum: 12
Labmda - Mu: 8 2 0
Sum: 12
Labmda - Mu: 2 8 0
Sum: 12


In [79]:
def H_potential_2D_y(
    states: int, site_x: int, site_y: int, V: np.ndarray, periodic: bool
) -> np.ndarray:

    sites = site_x * site_y

    # Create a matrix of the shape of Potential energy Hamiltonian filled with zeros.
    V_H = np.zeros((states**sites, states**sites), dtype=complex)

    print(V_H.shape)

    if periodic:
        site_range = sites
    else:
        site_range = sites - 1

    for y in range(site_x):
        for x in range(site_y):

            sites = site_x * site_y

            tail_x = site_index_matrix.T[y, x]
            head_x = site_index_matrix.T[y, (x + 1) % (site_y)]

            site_tail_x = np.minimum(tail_x, head_x)
            site_head_x = np.maximum(tail_x, head_x)

            n_lambda = state**(site_tail_x % (sites - 1))
            n_mu = state**(sites - 1 - site_head_x)
            n_nu = state**(np.abs(site_head_x - site_tail_x) - 1)

            if states**sites != n_lambda * n_mu * n_nu * states**2:
                raise ValueError("Wrong dimention")

            # Iterate through all elements of the Potential energy matrix operator.
            for q in range(states):
                for q_prime in range(states):
                    for p in range(states):
                        for p_prime in range(states):

                            # Calculate the flattened indices of the associated element.
                            row = p * states + q
                            col = p_prime * states + q_prime
                            val = V[row, col],

                            # Check if element is non zero.
                            if np.allclose(val, 0, atol=1e-25):
                                continue  # skip writing 0s

                            for Lambda in range(int(n_lambda)):
                                for mu in range(int(n_mu)):
                                    for nu in range(int(n_nu)):

                                        # Calculate the indices in the hamiltonian.
                                        i = (
                                            mu
                                            + q * n_mu
                                            + nu * states * n_mu
                                            + p * n_nu * n_mu * states
                                            + Lambda * n_nu * n_mu * states**2
                                        )
                                        j = (
                                            mu
                                            + q_prime * n_mu
                                            + nu * states * n_mu
                                            + p_prime * n_nu * n_mu * states
                                            + Lambda * n_nu * n_mu * states**2
                                        )

                                        # Assign a values to associated.
                                        V_H[i, j] += val
    return V_H

In [80]:
def H_potential_sparse_2D_y(
    state: int, site_x: int, site_y: int, V: np.ndarray, periodic: bool
) -> np.ndarray:

    sites = site_x * site_y

    dim = state**sites
    rows = []
    cols = []
    data = []

    # Use COO for fast iteration
    V = V.tocoo()

    if periodic:
        site_range = site
    else:
        site_range = site - 1

    for y in range(site_x):
        for x in range(site_y):
        # With x defining the first site of two-body interaction, we define the second dynamically.

            tail_x = site_index_matrix.T[y, x]
            head_x = site_index_matrix.T[y, (x + 1) % (site_y)]

            site_tail_x = np.minimum(tail_x, head_x)
            site_head_x = np.maximum(tail_x, head_x)

            n_lambda = state**(site_tail_x % (sites - 1))
            n_mu = state**(sites - 1 - site_head_x)
            n_nu = state**(np.abs(site_head_x - site_tail_x) - 1)

            # Define place values for state based numerical system.
            stride_q = n_mu
            stride_nu = state * n_mu
            stride_p = n_nu * n_mu * state
            stride_lambda = n_nu * n_mu * state ** 2

            # Create a new list of row, column and data indecies.
            for row_2s, col_2s, val in zip(
                V.row, V.col, V.data
            ):  # Iterate only through non-zero elements of the
                # Unflatten the indices.
                p, q = divmod(row_2s, state)
                p_prime, q_prime = divmod(col_2s, state)

                for Lambda in range(n_lambda):
                    for mu in range(n_mu):
                        for nu in range(n_nu):
                            # Calculate the indices in the hamiltonian.
                            i = mu + q * stride_q + nu * stride_nu + p * stride_p + Lambda * stride_lambda
                            j = mu + q_prime * stride_q + nu * stride_nu + p_prime * stride_p + Lambda * stride_lambda

                            # Uppend them to a new rows, collumns and data arrays.
                            rows.append(i)
                            cols.append(j)
                            data.append(val)

    rows = np.asarray(rows, dtype=np.float64)
    cols = np.asarray(cols, dtype=np.float64)
    data = np.asarray(data, dtype=np.float64)

    # Return a new sparse array of the potential energy part of the mamiltonian.
    return sp.csr_matrix((data, (rows, cols)), shape=(dim, dim), dtype=np.float64)

In [ ]:
K_s, V_s = build_V_in_p(state)

In [81]:
# V_2D_y = H_potential_2D_y(state, site_x, site_y, V_op.reshape(state**2, state**2), True)
V_2D_y = H_potential_sparse_2D_y(state, site_x, site_y, V_s, True)
V_old = H_potential_double(state, site_y, V_op.reshape(state**2, state**2), 1, True, False)


eig_val_2D_y, eig_vec_2D_y = sp.linalg.eigsh(V_2D_y, k=1, which='SA', tol=1e-19, maxiter=2000)
eig_val_old, eig_vec_old = np.linalg.eigh(V_old)

print(eig_val_2D_y[0] - np.min(eig_val_old) * site_x)

-1.7763568394002505e-15


### Potential diagonal (up ⇾ down)

In [115]:
for y in range(site_y):
    for x in range(site_x):

        tail = site_index_matrix[y, x]
        head = site_index_matrix[(y + 1) % (site_y), (x + 1) % (site_x)]

        print(np.minimum(tail, head), np.maximum(tail, head))

0 4
1 5
2 3
3 7
4 8
5 6
6 10
7 11
8 9
1 9
2 10
0 11


In [116]:
for y in range(site_y):
    for x in range(site_x):

        tail_x = site_index_matrix[y, x]
        head_x = site_index_matrix[(y + 1) % (site_y), (x + 1) % (site_x)]

        site_tail_x = np.minimum(tail_x, head_x)
        site_head_x = np.maximum(tail_x, head_x)

        n_lambda_x = (site_tail_x % (sites - 1))
        n_mu_x = (sites - 1 - site_head_x)
        n_nu_x = (np.abs(site_head_x - site_tail_x) - 1)

        # print("New:", site_1_x, site_2_x)

        print("Labmda - Mu:", n_lambda_x , n_nu_x, n_mu_x)
        print("Sum:", n_lambda_x + n_nu_x + n_mu_x + 2)

Labmda - Mu: 0 3 7
Sum: 12
Labmda - Mu: 1 3 6
Sum: 12
Labmda - Mu: 2 0 8
Sum: 12
Labmda - Mu: 3 3 4
Sum: 12
Labmda - Mu: 4 3 3
Sum: 12
Labmda - Mu: 5 0 5
Sum: 12
Labmda - Mu: 6 3 1
Sum: 12
Labmda - Mu: 7 3 0
Sum: 12
Labmda - Mu: 8 0 2
Sum: 12
Labmda - Mu: 1 7 2
Sum: 12
Labmda - Mu: 2 7 1
Sum: 12
Labmda - Mu: 0 10 0
Sum: 12


In [117]:
def H_potential_2D_diag_ud(
    states: int, site_x: int, site_y: int, V: np.ndarray, periodic: bool
) -> np.ndarray:

    sites = site_x * site_y

    # Create a matrix of the shape of Potential energy Hamiltonian filled with zeros.
    V_H = np.zeros((states**sites, states**sites), dtype=complex)

    print(V_H.shape)

    if periodic:
        site_range = sites
    else:
        site_range = sites - 1

    for y in range(site_y):
        for x in range(site_x):

            sites = site_x * site_y

            tail_x = site_index_matrix[y, x]
            head_x = site_index_matrix[(y + 1) % (site_y), (x + 1) % (site_x)]

            site_tail_x = np.minimum(tail_x, head_x)
            site_head_x = np.maximum(tail_x, head_x)

            n_lambda = state**(site_tail_x % (sites - 1))
            n_mu = state**(sites - 1 - site_head_x)
            n_nu = state**(np.abs(site_head_x - site_tail_x) - 1)

            if states**sites != n_lambda * n_mu * n_nu * states**2:
                raise ValueError("Wrong dimention")

            # Iterate through all elements of the Potential energy matrix operator.
            for q in range(states):
                for q_prime in range(states):
                    for p in range(states):
                        for p_prime in range(states):

                            # Calculate the flattened indices of the associated element.
                            row = p * states + q
                            col = p_prime * states + q_prime
                            val = V[row, col],

                            # Check if element is non zero.
                            if np.allclose(val, 0, atol=1e-25):
                                continue  # skip writing 0s

                            for Lambda in range(int(n_lambda)):
                                for mu in range(int(n_mu)):
                                    for nu in range(int(n_nu)):

                                        # Calculate the indices in the hamiltonian.
                                        i = (
                                            mu
                                            + q * n_mu
                                            + nu * states * n_mu
                                            + p * n_nu * n_mu * states
                                            + Lambda * n_nu * n_mu * states**2
                                        )
                                        j = (
                                            mu
                                            + q_prime * n_mu
                                            + nu * states * n_mu
                                            + p_prime * n_nu * n_mu * states
                                            + Lambda * n_nu * n_mu * states**2
                                        )

                                        # Assign a values to associated.
                                        V_H[i, j] += val
    return V_H

In [118]:
def H_potential_sparse_2D_diag_ud(
    state: int, site_x: int, site_y: int, V: np.ndarray, periodic: bool
) -> np.ndarray:

    sites = site_x * site_y

    dim = state**sites
    rows = []
    cols = []
    data = []

    # Use COO for fast iteration
    V = V.tocoo()

    if periodic:
        site_range = site
    else:
        site_range = site - 1

    for y in range(site_y):
        for x in range(site_x):
        # With x defining the first site of two-body interaction, we define the second dynamically.

            tail_x = site_index_matrix[y, x]
            head_x = site_index_matrix[(y + 1) % (site_y), (x + 1) % (site_x)]

            site_tail_x = np.minimum(tail_x, head_x)
            site_head_x = np.maximum(tail_x, head_x)

            n_lambda = state**(site_tail_x % (sites - 1))
            n_mu = state**(sites - 1 - site_head_x)
            n_nu = state**(np.abs(site_head_x - site_tail_x) - 1)

            # Define place values for state based numerical system.
            stride_q = n_mu
            stride_nu = state * n_mu
            stride_p = n_nu * n_mu * state
            stride_lambda = n_nu * n_mu * state ** 2

            # Create a new list of row, column and data indecies.
            for row_2s, col_2s, val in zip(
                V.row, V.col, V.data
            ):  # Iterate only through non-zero elements of the
                # Unflatten the indices.
                p, q = divmod(row_2s, state)
                p_prime, q_prime = divmod(col_2s, state)

                for Lambda in range(n_lambda):
                    for mu in range(n_mu):
                        for nu in range(n_nu):
                            # Calculate the indices in the hamiltonian.
                            i = mu + q * stride_q + nu * stride_nu + p * stride_p + Lambda * stride_lambda
                            j = mu + q_prime * stride_q + nu * stride_nu + p_prime * stride_p + Lambda * stride_lambda

                            # Uppend them to a new rows, collumns and data arrays.
                            rows.append(i)
                            cols.append(j)
                            data.append(val)

    rows = np.asarray(rows, dtype=np.float64)
    cols = np.asarray(cols, dtype=np.float64)
    data = np.asarray(data, dtype=np.float64)

    # Return a new sparse array of the potential energy part of the mamiltonian.
    return sp.csr_matrix((data, (rows, cols)), shape=(dim, dim), dtype=np.float64)

In [119]:
K_op, V_op = write_matrix_elements((state - 1)//2, 7 * np.pi/4)
V_op = basis_m_to_p_matrix_conversion(V_op.reshape(state, state, state, state), state)

In [120]:
K_s, V_s = build_V_in_p(state, 7 * np.pi/4)

In [121]:
# V_2D_diag_ud = H_potential_2D_diag_ud(state, site_x, site_y, V_op.reshape(state**2, state**2), True)
V_2D_diag_ud = H_potential_sparse_2D_diag_ud(state, site_x, site_y, V_s, True)
V_old = H_potential_double(state, site_x, V_op.reshape(state**2, state**2), 1, True, False)

eig_val_2D_diag_ud, eig_vec_2D_diag_ud = sp.linalg.eigsh(V_2D_diag_ud, k=1, which='SA', tol=1e-19, maxiter=2000)
eig_val_old, eig_vec_old = np.linalg.eigh(V_old)

print(eig_val_2D_diag_ud[0] - np.min(eig_val_old) * site_y)

-2.3034274862514073


In [110]:
np.min(eig_val_old)

np.float64(-0.9571067811865466)

In [107]:
eig_val_2D_diag_ud

array([-6.13185])

### Potential diagonal (down ⇾ up)

In [ ]:
for y in range(site_y):
    for x in range(site_x):

        site_index_matrix = np.arange(site_x * site_y).reshape(site_x, site_y)

        tail = site_index_matrix[y, x]
        head = site_index_matrix[(y - 1) % (site_y), (x + 1) % (site_x)]

        print(np.minimum(tail, head), np.maximum(tail, head))

0 7
1 8
2 6
1 3
2 4
0 5
4 6
5 7
3 8


In [10]:
site_x = 3
site_y = 3

sites = site_x * site_y

In [ ]:
for y in range(site_y - 1):
    for x in range(site_x):

        tail_x = site_x * y + x
        head_x = site_x * ((y+1) % (site_y)) + (x) % (site_x)

        site_tail_x = np.minimum(tail_x, head_x)
        site_head_x = np.maximum(tail_x, head_x)

        n_lambda_x = (site_tail_x % (sites - 1))
        n_mu_x = (sites - 1 - site_head_x)
        n_nu_x = (np.abs(site_head_x - site_tail_x) - 1)

        print("New:", site_head_x, site_tail_x)

        # print("Labmda - Mu:", n_lambda_x , n_nu_x, n_mu_x)
        # print("Sum:", n_lambda_x + n_nu_x + n_mu_x + 2)

New: 3 0
New: 4 1
New: 5 2
New: 6 3
New: 7 4
New: 8 5


In [ ]:
def H_potential_2D_diag_du(
    states: int, site_x: int, site_y: int, site_x_shift: int, site_y_shift: int, periodic_shift_x: int, periodic_shift_y: int, V: np.ndarray,
) -> np.ndarray:

    sites = site_x * site_y

    # Create a matrix of the shape of Potential energy Hamiltonian filled with zeros.
    V_H = np.zeros((states**sites, states**sites), dtype=complex)

    site_y_range = site_y - periodic_shift_x
    site_x_range = site_x - periodic_shift_y

    for y in range(site_y_range):
        for x in range(site_x_range):

            tail_x = site_x * y + x
            head_x = site_x * ((y + site_y_shift) % (site_y)) + (x + site_x_shift) % (site_x)

            site_tail_x = np.minimum(tail_x, head_x)
            site_head_x = np.maximum(tail_x, head_x)

            n_lambda = state**(site_tail_x % (sites - 1))
            n_mu = state**(sites - 1 - site_head_x)
            n_nu = state**(np.abs(site_head_x - site_tail_x) - 1)

            if states**sites != n_lambda * n_mu * n_nu * states**2:
                raise ValueError("Wrong dimention")

            # Iterate through all elements of the Potential energy matrix operator.
            for q in range(states):
                for q_prime in range(states):
                    for p in range(states):
                        for p_prime in range(states):

                            # Calculate the flattened indices of the associated element.
                            row = p * states + q
                            col = p_prime * states + q_prime
                            val = V[row, col],

                            # Check if element is non zero.
                            if np.allclose(val, 0, atol=1e-25):
                                continue  # skip writing 0s

                            for Lambda in range(int(n_lambda)):
                                for mu in range(int(n_mu)):
                                    for nu in range(int(n_nu)):

                                        # Calculate the indices in the hamiltonian.
                                        i = (
                                            mu
                                            + q * n_mu
                                            + nu * states * n_mu
                                            + p * n_nu * n_mu * states
                                            + Lambda * n_nu * n_mu * states**2
                                        )
                                        j = (
                                            mu
                                            + q_prime * n_mu
                                            + nu * states * n_mu
                                            + p_prime * n_nu * n_mu * states
                                            + Lambda * n_nu * n_mu * states**2
                                        )

                                        # Assign a values to associated.
                                        V_H[i, j] += val
    return V_H

NameError: name 'np' is not defined

In [ ]:
K_op, V_op = write_matrix_elements((state - 1)//2, np.pi/4)
V_op = basis_m_to_p_matrix_conversion(V_op.reshape(state, state, state, state), state)

In [ ]:
V_2D_diag_du = H_potential_2D_diag_du(state, site_x, site_y, V_op.reshape(state**2, state**2), True)
V_old = H_potential_double(state, site_x, V_op.reshape(state**2, state**2), 1, True, False)

eig_val_2D_diag_du, eig_vec_2D_diag_du = sp.linalg.eigsh(sp.csc_matrix(V_2D_diag_du), k=1, which='SA', tol=1e-19, maxiter=2000)
eig_val_old, eig_vec_old = np.linalg.eigh(V_old)

print(eig_val_2D_diag_du[0] - np.min(eig_val_old) * site_y)

(19683, 19683)


/var/folders/vt/f4sbj2d11gbbb9q5816khz2m0000gn/T/ipykernel_41228/60051894.py:71: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  V_H[i, j] += val


-1.2878587085651816e-14


# CCC 2D

In [3]:
state = 3
site = 5

In [4]:
K_op, V_op = write_matrix_elements((state - 1)//2)

In [5]:
K_op = basis_m_to_p_matrix_conversion(K_op, state)
V_op = basis_m_to_p_matrix_conversion(V_op.reshape(state, state, state, state), state)

In [6]:
t_2_2D = np.zeros((site, site))

In [ ]:
for i in range(1, site+1):
    for j in range(i, site+1):

        t_2_2D[i-1, j-1] = (i * 10) + j

        tail_x = x + dim_x * y
        head_x = dim_x*((y + shift_y) % (dim_y)) + ((x + shift_x) % (dim_x))

        site_tail_x = np.minimum(tail_x, head_x)
        site_head_x = np.maximum(tail_x, head_x)

print(t_2_2D)

[[11. 12. 13. 14. 15.]
 [ 0. 22. 23. 24. 25.]
 [ 0.  0. 33. 34. 35.]
 [ 0.  0.  0. 44. 45.]
 [ 0.  0.  0.  0. 55.]]
