In [4]:
import os
import numpy as np

from quant_rotor.core.dense.t_amplitudes_periodic import t_periodic

# Dense (Slow)
from quant_rotor.core.dense.hamiltonian import hamiltonian_dense
from quant_rotor.core.dense.hamiltonian_big import hamiltonian_general_dense

# Sparse (Fast)
from quant_rotor.core.sparse.hamiltonian import hamiltonian_sparse
from quant_rotor.core.sparse.hamiltonian_big import hamiltonian_general_sparse

In [5]:
np.set_printoptions(precision=5)
np.set_printoptions(suppress=True)
np.set_printoptions(linewidth=np.inf)
np.set_printoptions(threshold=np.inf)

# Setup Parallel Processing

In [6]:
print("Logical cores:", os.cpu_count())

Logical cores: 10


# Access to sites

In [7]:
site = 5

In [8]:
t_2 = np.zeros((site))

In [11]:
for i in range(1, site):
    t_2[i] = i / 10
print(t_2)

[0.  0.1 0.2 0.3 0.4]


In [12]:
site = 5
dim = 2

In [13]:
t_2 = np.zeros((site, dim))

In [14]:
for i in range(dim):
    for j in range(1, site):
        t_2[j, i] = j / 10

print(t_2)

[[0.  0. ]
 [0.1 0.1]
 [0.2 0.2]
 [0.3 0.3]
 [0.4 0.4]]


In [15]:
I, J = np.indices((3, 3))

In [16]:
coords = np.stack((I, J), axis=-1)
print(coords)

[[[0 0]
  [0 1]
  [0 2]]

 [[1 0]
  [1 1]
  [1 2]]

 [[2 0]
  [2 1]
  [2 2]]]


In [17]:
t_2_2D = np.zeros((site, site))

In [18]:
for i in range(1, site+1):
    for j in range(i, site+1):
        t_2_2D[i-1, j-1] = (i * 10) + j

print(t_2_2D)

[[11. 12. 13. 14. 15.]
 [ 0. 22. 23. 24. 25.]
 [ 0.  0. 33. 34. 35.]
 [ 0.  0.  0. 44. 45.]
 [ 0.  0.  0.  0. 55.]]


In [25]:
site = 7

In [26]:
t_2_3D = np.zeros((site-1, site-1, site-1))

for i in range(1, site):
    for j in range(i, site):
        for k in range(j, site):
            t_2_3D[i-1, j-1, k - 1] = 100 * i + 10 * j + k

print(t_2_3D)

[[[111. 112. 113. 114. 115. 116.]
  [  0. 122. 123. 124. 125. 126.]
  [  0.   0. 133. 134. 135. 136.]
  [  0.   0.   0. 144. 145. 146.]
  [  0.   0.   0.   0. 155. 156.]
  [  0.   0.   0.   0.   0. 166.]]

 [[  0.   0.   0.   0.   0.   0.]
  [  0. 222. 223. 224. 225. 226.]
  [  0.   0. 233. 234. 235. 236.]
  [  0.   0.   0. 244. 245. 246.]
  [  0.   0.   0.   0. 255. 256.]
  [  0.   0.   0.   0.   0. 266.]]

 [[  0.   0.   0.   0.   0.   0.]
  [  0.   0.   0.   0.   0.   0.]
  [  0.   0. 333. 334. 335. 336.]
  [  0.   0.   0. 344. 345. 346.]
  [  0.   0.   0.   0. 355. 356.]
  [  0.   0.   0.   0.   0. 366.]]

 [[  0.   0.   0.   0.   0.   0.]
  [  0.   0.   0.   0.   0.   0.]
  [  0.   0.   0.   0.   0.   0.]
  [  0.   0.   0. 444. 445. 446.]
  [  0.   0.   0.   0. 455. 456.]
  [  0.   0.   0.   0.   0. 466.]]

 [[  0.   0.   0.   0.   0.   0.]
  [  0.   0.   0.   0.   0.   0.]
  [  0.   0.   0.   0.   0.   0.]
  [  0.   0.   0.   0.   0.   0.]
  [  0.   0.   0.   0. 555. 556.]
  [  0

# Building the potential.