In [1]:
import numpy as np
import matplotlib.pyplot as plt

from quant_rotor.CCC_iterative_methods.Dense.t_amplitudes_periodic import t_periodic

from quant_rotor.Hamiltonian_models.Dense.hamiltonian import hamiltonian_dense as ham
from quant_rotor.Hamiltonian_models.Dense.heisenberg_operators import heisenberg_operators
from quant_rotor.Hamiltonian_models.Dense.rotor_operators import rotor_operators

from quant_rotor.Hamiltonian_models.Dense.NO_transfrorm import NO_transform
from quant_rotor.Hamiltonian_models.Dense.combine_hamiltonian import combine_hamiltonian as ham_comb

from quant_rotor.CCC_iterative_methods.Dense.t_amplitudes_guess import t_1_amplitude_guess_ground_state, t_2_amplitude_guess_ground_state, amplitute_energy, intermediate_normalisation

In [2]:
np.set_printoptions(precision=10)
np.set_printoptions(suppress=True)
np.set_printoptions(linewidth=np.inf)
np.set_printoptions(threshold=np.inf)

# Initialization Rotor

In [88]:
state = 5
site = 2

p = state
i = 1
a = p - i

g = 0.1
periodic = False

In [89]:
K, V = rotor_operators(state, g)
H = ham(site, K, V, V, periodic)

In [90]:
V = V.reshape(state, state, state, state)

In [91]:
eig_val, eig_vec = np.linalg.eigh(H)

In [92]:
t_1_exact = t_1_amplitude_guess_ground_state(state, site, eig_vec, eig_val)
t_2_exact = t_2_amplitude_guess_ground_state(state, site, eig_vec, eig_val)

In [93]:
t_1_exact_safe = t_1_amplitude_guess_ground_state(state, site, eig_vec, eig_val)
t_2_exact_safe = t_2_amplitude_guess_ground_state(state, site, eig_vec, eig_val)

In [94]:
V_xy = V
V_yx = V

# Initialization Combined Rotor

In [3]:
n_comb_sites = 2
site_comb = 2
site = n_comb_sites * site_comb

state = 3
state_comb = state**site_comb

p = state
i = 1
a = p - i

g = 0.1
periodic = False

In [4]:
K, V = rotor_operators(state, g)
H = ham(site, K, V, V, periodic)

In [5]:
H_comb, K_comb, V_comb_xy, V_comb_yx = ham_comb(site, site_comb, K, V, periodic)

eig_val_comb, eig_vec_comb = np.linalg.eigh(H_comb)

In [6]:
V_total = V_comb_xy + V_comb_yx

In [7]:
V = V.reshape(state, state, state, state)

In [8]:
eig_val, eig_vec = np.linalg.eigh(H)

In [9]:
eig_val

array([-0.0187195658,  0.8261749988,  0.9101243891,  0.9322308373,  0.9594363293,  1.0212865813,  1.0551510902,  1.0717261959,  1.1489698656,  1.7766814416,  1.8248448096,  1.8248448096,  1.8867690618,  1.8993630483,  1.9078054294,  1.9078054294,  1.9475269347,  1.9923678838,  1.9948480197,  1.9948480197,  1.9956330771,  1.9970483536,  1.9989185425,  1.9989185425,  2.0062143414,  2.0474855123,  2.0872592205,  2.0872592205,  2.0993877324,  2.1102371092,  2.1675936592,  2.1675936592,  2.2225440859,  2.8489617896,  2.8591057046,  2.8592990161,  2.8719223594,  2.8792893219,  2.8869501186,  2.8872620922,  2.9219223594,  2.922004649 ,  2.9425799116,  2.9568584542,  2.9569510255,  2.9673180059,  2.9680066663,  2.9709467025,  2.9792893219,  3.0207106781,  3.0314908545,  3.0366992146,  3.0370039312,  3.044145046 ,  3.044187012 ,  3.0656852376,  3.0780776406,  3.08343738  ,  3.1155587728,  3.1157612916,  3.1207106781,  3.1280776406,  3.1509772239,  3.1511371557,  3.1725724566,  4.          ,  4.

In [10]:
eig_val_comb

array([-0.0187195658,  0.8261749988,  0.9101243891,  0.9322308373,  0.9594363293,  1.0212865813,  1.0551510902,  1.0717261959,  1.1489698656,  1.7766814416,  1.8248448096,  1.8248448096,  1.8867690618,  1.8993630483,  1.9078054294,  1.9078054294,  1.9475269347,  1.9923678838,  1.9948480197,  1.9948480197,  1.9956330771,  1.9970483536,  1.9989185425,  1.9989185425,  2.0062143414,  2.0474855123,  2.0872592205,  2.0872592205,  2.0993877324,  2.1102371092,  2.1675936592,  2.1675936592,  2.2225440859,  2.8489617896,  2.8591057046,  2.8592990161,  2.8719223594,  2.8792893219,  2.8869501186,  2.8872620922,  2.9219223594,  2.922004649 ,  2.9425799116,  2.9568584542,  2.9569510255,  2.9673180059,  2.9680066663,  2.9709467025,  2.9792893219,  3.0207106781,  3.0314908545,  3.0366992146,  3.0370039312,  3.044145046 ,  3.044187012 ,  3.0656852376,  3.0780776406,  3.08343738  ,  3.1155587728,  3.1157612916,  3.1207106781,  3.1280776406,  3.1509772239,  3.1511371557,  3.1725724566,  4.          ,  4.

In [11]:
t_1_exact = t_1_amplitude_guess_ground_state(state_comb, site_comb, eig_vec_comb, eig_val_comb)
t_2_exact = t_2_amplitude_guess_ground_state(state_comb, site_comb, eig_vec_comb, eig_val_comb)

In [12]:
t_1_exact

array([[[-0.          +0.j],
        [-0.          +0.j],
        [-0.          +0.j],
        [ 0.0374066368+0.j],
        [ 0.0125311275+0.j],
        [-0.          +0.j],
        [ 0.0125311275+0.j],
        [ 0.0374066368+0.j]],

       [[ 0.          +0.j],
        [-0.          +0.j],
        [-0.          +0.j],
        [ 0.0374066368+0.j],
        [ 0.0125311275+0.j],
        [-0.          +0.j],
        [ 0.0125311275+0.j],
        [ 0.0374066368+0.j]]])

In [13]:
t_1_exact_orig = t_1_amplitude_guess_ground_state(state, site, eig_vec, eig_val)
t_2_exact_orig = t_2_amplitude_guess_ground_state(state, site, eig_vec, eig_val)

In [14]:
K = K_comb
V_xy = V_comb_xy.reshape(state_comb, state_comb, state_comb, state_comb)
V_yx = V_comb_yx.reshape(state_comb, state_comb, state_comb, state_comb)

p = state_comb
i = 1
a = p - i

site = site_comb
state = state_comb

In [15]:
# K = K
# V_xy = V.reshape(state, state, state, state)
# V_yx = V.reshape(state, state, state, state)

# p = state
# i = 1
# a = p - i

# Initialization Magnetic

In [17]:
n_comb_sites = 4
site_comb = 2
site = n_comb_sites * site_comb

state = 2
state_comb = state**n_comb_sites

J_x = 1
J_y = 1
J_z = 0

h_x = 0
h_y = 0
h_z = -1

g = 0.9

periodic = False

In [18]:
p = state_comb
i = 1
a = p - i

In [19]:
K, V = heisenberg_operators(J_x, J_y, J_z, h_x, h_y, h_z, g)
H = ham(site, K, V, V, periodic)

eig_val, eig_vec = np.linalg.eigh(H)

In [20]:
H_comb, K_comb, V_comb_xy, V_comb_yx = ham_comb(site, site_comb, K, V, periodic)

eig_val_comb, eig_vec_comb = np.linalg.eigh(H_comb)

In [21]:
K_NO, V_NO_xy, basis = NO_transform(state_comb, state_comb, H_comb, K_comb, V_comb_xy)

matrix_p_to_NO_V = np.kron(basis, basis)
V_NO_yx = matrix_p_to_NO_V.conj().T @ V_comb_yx @ matrix_p_to_NO_V

[-0.           -0.           -0.           -0.           -0.           -0.            0.            0.            0.            0.            0.            0.            0.0047550948  0.0642021006  0.0642021006  0.866840704 ]
[[-0.          +0.j -0.          +0.j -0.          +0.j  0.          +0.j -0.          +0.j  0.          -0.j -0.          +0.j -0.          -0.j  0.          +0.j  0.          +0.j  0.          +0.j -0.          -0.j -0.          -0.j  0.999999998 +0.j -0.0000637286+0.j  0.          +0.j]
 [ 0.220055535 +0.j  0.0173456785+0.j -0.005217583 +0.j -0.011933225 +0.j  0.0082052113+0.j  0.          +0.j  0.          +0.j -0.          +0.j  0.          +0.j  0.          +0.j -0.0025934892+0.j  0.274194714 +0.j  0.8159366616+0.j  0.          +0.j -0.          +0.j  0.4583619044+0.j]
 [ 0.6339951981+0.j  0.0274778937+0.j -0.0044105175+0.j -0.0306659253+0.j  0.0221310608+0.j  0.          +0.j  0.          +0.j -0.          +0.j  0.          +0.j  0.          +0.j -0.0138498

In [22]:
H_NO = ham(site_comb, K_NO, V_NO_xy, V_NO_yx, periodic)

eig_val_NO, eig_vec_NO = np.linalg.eigh(H_NO)

In [23]:
t_1_exact = t_1_amplitude_guess_ground_state(state_comb, site_comb, eig_vec_NO, eig_val_NO)
t_2_exact = t_2_amplitude_guess_ground_state(state_comb, site_comb, eig_vec_NO, eig_val_NO)

In [24]:
site = site_comb

K = K_NO

V_xy = V_NO_xy.reshape(state_comb, state_comb, state_comb, state_comb)
V_yx = V_NO_yx.reshape(state_comb, state_comb, state_comb, state_comb)

In [25]:
_, E_0, E = amplitute_energy(site_comb, state_comb, periodic, K_NO, V_xy, V_yx, t_1_exact, t_2_exact)

# Implementation Linked

In [16]:
t_1 = t_1_exact
t_2 = t_2_exact


## Functions

In [17]:
def h_term(h_upper, h_lower):
    a_h_shift = [i if a_check == a else 0 for a_check in (h_upper, h_lower)]
    return K[a_h_shift[0]:h_upper + a_h_shift[0], a_h_shift[1]:h_lower + a_h_shift[1]]

In [18]:
def v_func(x: int, y: int, idx_up_1: int, idx_up_2: int, idx_low_1: int, idx_low_2: int):
    a_v_shift = [
            i if a_check == a else 0
            for a_check in (idx_up_1, idx_up_2, idx_low_1, idx_low_2)
        ]
    if (x - y) == 1:

        return V_yx[
            a_v_shift[0] : idx_up_1 + a_v_shift[0],
            a_v_shift[1] : idx_up_2 + a_v_shift[1],
            a_v_shift[2] : idx_low_1 + a_v_shift[2],
            a_v_shift[3] : idx_low_2 + a_v_shift[3],
        ]

    if (y - x) == 1:

        return V_xy[
            a_v_shift[0] : idx_up_1 + a_v_shift[0],
            a_v_shift[1] : idx_up_2 + a_v_shift[1],
            a_v_shift[2] : idx_low_1 + a_v_shift[2],
            a_v_shift[3] : idx_low_2 + a_v_shift[3],
        ]

    else:
        return np.zeros((idx_up_1, idx_up_2, idx_low_1, idx_low_2), dtype=complex)

In [19]:
def A_term(a_upper, a_site):
    return np.hstack((-t_1[a_site], np.identity(a_upper)))

def B_term(b_lower, b_site):
    return np.vstack((np.identity(b_lower), t_1[b_site]))

In [20]:
def t_1_func(x: int):
    return t_1[x]

In [21]:
def t_2_func(x: int, y: int):
    return t_2[x, y]

In [22]:
def ec1(x: int):
    return np.einsum("ia, ai", h_term(i, a), t_1_func(x))

In [23]:
def ec2(x: int, y: int):

    term = t_2_func(x, y) + np.einsum("ai, bj-> abij", t_1_func(x), t_1_func(y))

    return np.einsum("ijab, abij", v_func(x, y, i, i, a, a), term)

In [24]:
def et1(x: int):
    term = ec1(x)

    for z in range(site):
        if x != z:
            term += ec2(x, z)

    return term

In [25]:
def E_tot():
    for x in range(site):
        term = ec1(x)

        for y in range(site):
            if x != y:
                term += ec2(x, y) / 2

In [26]:
def c1(x: int):
    return np.einsum("aq, qi -> ai", h_term(a, p), B_term(i, x))

In [27]:
def c2(x: int, z: int):
    term = np.einsum("alcd, cdil -> ai", v_func(x, z, a, i, a, a), t_2_func(x, z))
    term += np.einsum("alqs, qi, sl -> ai", v_func(x, z, a, i, p, p), B_term(i, x), B_term(i, z))
    return term

In [28]:
def c3(x: int, z: int, w: int):
    return np.einsum("acik, klcp, pl -> ai", t_2_func(x, w), v_func(w, z, i, i, a, p), B_term(i, z))

In [29]:
def R_1(x: int):
    term = c1(x)
    for z in range(site):
        if z != x:
            term += c2(x, z)
            for w in range(site):
                if (w != x) and (w != z):
                    term += c3(x, z, w) - et1(x) * t_1_func(x)
    return term

In [30]:
def R_2_sym(x: int, y: int):
    term = np.einsum("abrs, ri, sj -> abij", v_func(x, y, a, a, p, p), B_term(i, x), B_term(i, y))
    term += np.einsum("abcd, cdij -> abij", v_func(x, y, a, a, a, a), t_2_func(x, y))
    for z in range(site):
        for w in range(site):
            if z not in {x, y} and w not in {x, y} and z != w:
                term += np.einsum("klcd, acik, bdjl -> abij", v_func(z, w, i, i, a, a) ,t_2_func(y, w))

    term -= t_2_func(x, y) * (et1(x) + et1(y) - ec2(x, y))
    term += np.einsum("ai, bj -> abij", t_1_func(x), t_1_func(y)) * ec2(x, y)

    return term

In [31]:
def R_2_non_sym(x: int, y: int):

    term_intermediet = np.zeros((a, i), dtype=complex)

    term = np.einsum("ac, cbij -> abij", h_term(a, a), t_2_func(x, y))

    for z in range(site):
        if (z != x) and (z != y):
            term += np.einsum("acik, kbcs, sj -> abij", t_2_func(x, z), v_func(z, y, i, a, a, p), B_term(i, y))
            term += np.einsum("blds, adij, sl -> abij", v_func(y, z, a, a, i, i), t_2_func(x, y), B_term(i, z))
            term_intermediet += c3(x, y, z) + c3(x, z, y)

    term -= np.einsum("ai, bj -> abij", (c2(x, y) + term_intermediet), t_1_func(y))
    return term

In [32]:
def R_2_total(x: int, y: int):
    return R_2_sym(x, y) + R_2_non_sym(x, y) + R_2_non_sym(y, x)

# Test

In [27]:
single = np.zeros((site, a, i), dtype=complex)
double = np.zeros((site, site, a, a, i, i), dtype=complex)

In [28]:
for x_site in range(site):
    single[x_site] = R_1(x_site)
    for y_site in range(site):
        if x_site < y_site:
            print(c2(x_site, y_site))
            double[x_site, y_site] = R_2_total(x_site, y_site)

[[-0.          +0.j]
 [-0.          +0.j]
 [-0.0018724479+0.j]
 [-0.0018724479+0.j]]


In [37]:
np.max(np.abs(single))

np.float64(2.9146288953825136e-06)

In [38]:
np.max(np.abs(double))

np.float64(2.7755575615628914e-17)

# Implementation T1-transformed Linked

In [33]:
t_1 = t_1_exact
t_2 = t_2_exact

In [34]:
t_1_exact

array([[[-0.          +0.j],
        [-0.          +0.j],
        [-0.          +0.j],
        [ 0.0374066368+0.j],
        [ 0.0125311275+0.j],
        [-0.          +0.j],
        [ 0.0125311275+0.j],
        [ 0.0374066368+0.j]],

       [[ 0.          +0.j],
        [-0.          +0.j],
        [-0.          +0.j],
        [ 0.0374066368+0.j],
        [ 0.0125311275+0.j],
        [-0.          +0.j],
        [ 0.0125311275+0.j],
        [ 0.0374066368+0.j]]])

In [64]:
t_2_exact[0, 1].reshape(a, a) - t_2_exact[1, 0].reshape(a, a)

array([[ 0.          +0.j,  0.          +0.j,  0.0370825071+0.j,  0.          +0.j, -0.          +0.j,  0.012329781 +0.j,  0.          +0.j,  0.          +0.j],
       [ 0.          +0.j,  0.          +0.j,  0.012329781 +0.j, -0.          +0.j, -0.          +0.j,  0.0370825071+0.j, -0.          +0.j, -0.          +0.j],
       [-0.0370825071+0.j, -0.012329781 +0.j,  0.          +0.j, -0.          +0.j, -0.          +0.j,  0.          +0.j, -0.          +0.j, -0.          +0.j],
       [-0.          +0.j,  0.          +0.j,  0.          +0.j,  0.          +0.j,  0.0000028905+0.j,  0.          +0.j, -0.0000028905+0.j,  0.          +0.j],
       [ 0.          +0.j,  0.          +0.j,  0.          +0.j, -0.0000028905+0.j,  0.          +0.j,  0.          +0.j,  0.          +0.j,  0.0000028905+0.j],
       [-0.012329781 +0.j, -0.0370825071+0.j,  0.          +0.j, -0.          +0.j, -0.          +0.j,  0.          +0.j, -0.          +0.j, -0.          +0.j],
       [-0.          +0.j,  0.    

In [61]:
t_2_exact[1, 0].reshape(a, a)

array([[ 0.0018748225+0.j,  0.0031078142+0.j,  0.0003471164+0.j, -0.          +0.j, -0.          +0.j,  0.0002705893+0.j, -0.          +0.j, -0.          +0.j],
       [ 0.0031078142+0.j,  0.0018748225+0.j,  0.0002705893+0.j,  0.          +0.j,  0.          +0.j,  0.0003471164+0.j,  0.          +0.j,  0.          +0.j],
       [ 0.0374296235+0.j,  0.0126003703+0.j,  0.0018748225+0.j, -0.          +0.j, -0.          +0.j,  0.0031078142+0.j, -0.          +0.j, -0.          +0.j],
       [-0.          +0.j, -0.          +0.j, -0.          +0.j,  0.0000034364+0.j, -0.0000000213+0.j, -0.          +0.j,  0.0000028692+0.j, -0.0000013584+0.j],
       [-0.          +0.j, -0.          +0.j, -0.          +0.j,  0.0000028692+0.j,  0.0000005636+0.j, -0.          +0.j,  0.0000053584+0.j, -0.0000000213+0.j],
       [ 0.0126003703+0.j,  0.0374296235+0.j,  0.0031078142+0.j,  0.          +0.j,  0.          +0.j,  0.0018748225+0.j,  0.          +0.j,  0.          +0.j],
       [-0.          +0.j, -0.    

## Functions

In [35]:
def A_term_big(a_site):
    vec = np.vstack((np.identity(i), -t_1[a_site]))

    return np.hstack((vec, np.identity(p)[:, 1:]))

def B_term_big(b_site):
    vec = np.vstack((np.identity(i), t_1[b_site]))
    return np.hstack((vec, np.identity(p)[:, 1:]))

In [36]:
def h_bar_term(x: int, h_upper: int, h_lower: int):
    K_bar = np.einsum("ps, sq, qr -> pr", A_term_big(x), h_term(p, p),  B_term_big(x))
    K_bar -= np.eye(p) * K_bar[0,0]

    a_h_shift = [i if a_check == a else 0 for a_check in (h_upper, h_lower)]
    return K_bar[a_h_shift[0]:h_upper + a_h_shift[0], a_h_shift[1]:h_lower + a_h_shift[1]]

In [37]:
h_bar_term(0, a, i)

array([[-0.          +0.j],
       [-0.          +0.j],
       [-0.          +0.j],
       [ 0.0000465994+0.j],
       [ 0.0001404185+0.j],
       [-0.          +0.j],
       [ 0.0001404185+0.j],
       [ 0.0000465994+0.j]])

In [38]:
h_bar_term(1, a, i)

array([[ 0.          +0.j],
       [-0.          +0.j],
       [-0.          +0.j],
       [ 0.0000465994+0.j],
       [ 0.0001404185+0.j],
       [-0.          +0.j],
       [ 0.0001404185+0.j],
       [ 0.0000465994+0.j]])

In [39]:
def v_bar_term(x: int, y: int, idx_up_1: int, idx_up_2: int, idx_low_1: int, idx_low_2: int):

    V_xy_bar = np.einsum("pP, qQ, PQRS, Rr, Ss -> pqrs", A_term_big(x), A_term_big(y), v_func(x, y, p, p, p, p),  B_term_big(x), B_term_big(y))
    V_yx_bar = np.einsum("pP, qQ, PQRS, Rr, Ss -> pqrs", A_term_big(y), A_term_big(x), v_func(y, x, p, p, p, p),  B_term_big(y), B_term_big(x))
    for indx_1 in range(p):
        for indx_2 in range(p):
            V_xy_bar[indx_1, indx_2, indx_1, indx_2] -= V_xy_bar[0, 0, 0, 0]
            V_yx_bar[indx_1, indx_2, indx_1, indx_2] -= V_yx_bar[0, 0, 0, 0]

    a_v_shift = [
            i if a_check == a else 0
            for a_check in (idx_up_1, idx_up_2, idx_low_1, idx_low_2)
        ]
    if (x - y) == 1:

        return V_yx_bar[
            a_v_shift[0] : idx_up_1 + a_v_shift[0],
            a_v_shift[1] : idx_up_2 + a_v_shift[1],
            a_v_shift[2] : idx_low_1 + a_v_shift[2],
            a_v_shift[3] : idx_low_2 + a_v_shift[3],
        ]

    if (y - x) == 1:

        return V_xy_bar[
            a_v_shift[0] : idx_up_1 + a_v_shift[0],
            a_v_shift[1] : idx_up_2 + a_v_shift[1],
            a_v_shift[2] : idx_low_1 + a_v_shift[2],
            a_v_shift[3] : idx_low_2 + a_v_shift[3],
        ]

    else:
        return np.zeros((idx_up_1, idx_up_2, idx_low_1, idx_low_2), dtype=complex)

In [40]:
h_bar_term(1, a, i)/2

array([[ 0.          +0.j],
       [-0.          +0.j],
       [-0.          +0.j],
       [ 0.0000232997+0.j],
       [ 0.0000702093+0.j],
       [-0.          +0.j],
       [ 0.0000702093+0.j],
       [ 0.0000232997+0.j]])

In [41]:
np.einsum("alcd, cdil -> ai", v_bar_term(0, 1, a, i, a, a), t_2_func(0, 1))

array([[-0.          +0.j],
       [-0.          +0.j],
       [-0.          +0.j],
       [-0.0000463723+0.j],
       [-0.0001400569+0.j],
       [-0.          +0.j],
       [-0.0001400569+0.j],
       [-0.0000463723+0.j]])

In [42]:
np.einsum("alcd, cdil -> ai", v_bar_term(1, 0, a, i, a, a), t_2_func(1, 0))

array([[-0.          +0.j],
       [-0.          +0.j],
       [ 0.          +0.j],
       [-0.0002775029+0.j],
       [-0.000217485 +0.j],
       [ 0.          +0.j],
       [-0.000217485 +0.j],
       [-0.0002775029+0.j]])

In [43]:
np.einsum("lbcd, dclj -> bj", v_bar_term(0, 1, i, a, a, a), t_2_func(0, 1))

array([[ 0.          +0.j],
       [-0.          +0.j],
       [-0.          +0.j],
       [-0.0002775029+0.j],
       [-0.000217485 +0.j],
       [-0.          +0.j],
       [-0.000217485 +0.j],
       [-0.0002775029+0.j]])

In [44]:
np.einsum("lbdc, dclj -> bj", v_func(0, 1, i, a, a, a), t_2_func(0, 1))

array([[ 0.          +0.j],
       [ 0.          +0.j],
       [ 0.          +0.j],
       [-0.0002799566+0.j],
       [-0.000218307 +0.j],
       [ 0.          +0.j],
       [-0.000218307 +0.j],
       [-0.0002799566+0.j]])

In [45]:
np.einsum("alcd, cdil -> ai", v_func(0, 1, a, i, a, a), t_2_func(0, 1))

array([[ 0.          +0.j],
       [ 0.          +0.j],
       [-0.          +0.j],
       [-0.0002799566+0.j],
       [-0.000218307 +0.j],
       [-0.          +0.j],
       [-0.000218307 +0.j],
       [-0.0002799566+0.j]])

In [46]:
np.max(np.abs(v_func(0, 1, i, a, a, a)))

np.float64(0.07500000000000001)

In [47]:
np.max(np.abs(v_func(0, 1, a, i, a, a)))

np.float64(0.07500000000000001)

In [48]:
def e_bar_c(x: int, y: int):
    return np.einsum("ijab, abij", v_bar_term(x, y, i, i, a, a), t_2_func(x, y))

In [49]:
def E_c(x: int):
    term = 0
    for z in range(site):
        if x != z:
            term += e_bar_c(x, z)
    return term

In [50]:
def R_bar_1(x: int):
    term = h_bar_term(x, a, i)
    for z in range(site):
        if x != z:
            term += np.einsum("alcd, cdil -> ai", v_bar_term(x, z, a, i, a, a), t_2_func(x, z))
            for w in range(site):
                if (w != x) and (w != z):
                    term += np.einsum("acik, klcl -> ai", t_2_func(x, w),  v_bar_term(z, w, i, i, i, a))
    return term

In [51]:
def R_bar_2_sym(x: int, y: int):
    term = v_bar_term(x, y, a, a, i, i)

    # print(term)
    term += np.einsum("abcd, cdij -> abij", v_bar_term(x, y, a, a, a, a), t_2_func(x, y))

    # print("Term_1", np.einsum("abcd, cdij -> abij", v_bar_term(x, y, a, a, a, a), t_2_func(x, y)))
    for z in range(site):
        for w in range(site):
            if z not in {x, y} and w not in {x, y} and z != w:
                term += np.einsum("klcd, acik, bdjl -> abij", v_bar_term(z, w, i, i, a, a), t_2_func(x, z), t_2_func(y, w))

    term -= t_2_func(x, y)*(E_c(x) + E_c(y) - e_bar_c(x, y))

    print(E_c(x) + E_c(y) - e_bar_c(x, y))
    return term

In [52]:
def R_bar_2_non_sym(x: int, y: int):
    term = np.einsum("ac, cbij -> abij", h_bar_term(x, a, a) , t_2_func(x, y))

    # print( h_bar_term(x, a, a))

    for z in range(site):
        if z not in {x, y}:
            term += np.einsum("acik, kbcj -> abij", t_2_func(x, z), v_bar_term(z, y, i, a, a, i))
            term += np.einsum("bldl, adij -> abij", v_bar_term(y, z, a, i, a, i), t_2_func(x, y))
    return term

In [53]:
def R_bar_2_total(x, y):
    return R_bar_2_sym(x, y) + R_bar_2_non_sym(x, y) + R_bar_2_non_sym(y, x)

In [54]:
def R_n_term(x, y):
    x_y = np.einsum("bj, jc, acij -> abij", t_1_func(y), h_term(i, a), t_2_func(x, y))
    y_x = np.einsum("bj, jc, acij -> abij", t_1_func(x), h_term(i, a), t_2_func(y, x))
    return x_y + y_x

# Test

In [55]:
single_new = np.zeros((site, a, i), dtype=complex)
double_new = np.zeros((site, site, a, a, i, i), dtype=complex)
double_test = np.zeros((site, site, a, a, i, i), dtype=complex)

In [56]:
for x_site in range(site):
    single_new[x_site] = R_bar_1(x_site)
    for y_site in range(site):
        if x_site < y_site:
            double_new[x_site, y_site] = R_bar_2_total(x_site, y_site)

            double_test[x_site, y_site] = R_n_term(x_site, y_site)

(-6.55969179897244e-05+0j)


In [57]:
single_new

array([[[-0.          +0.j],
        [-0.          +0.j],
        [-0.          +0.j],
        [ 0.000000227 +0.j],
        [ 0.0000003616+0.j],
        [-0.          +0.j],
        [ 0.0000003616+0.j],
        [ 0.000000227 +0.j]],

       [[ 0.          +0.j],
        [-0.          +0.j],
        [-0.          +0.j],
        [-0.0002309035+0.j],
        [-0.0000770665+0.j],
        [-0.          +0.j],
        [-0.0000770665+0.j],
        [-0.0002309035+0.j]]])

In [58]:
np.max(np.abs(single_new))

np.float64(0.0002309035184713335)

In [173]:
np.max(np.abs(double_new))

np.float64(0.03745491622535635)

In [106]:
np.max(double_test)

np.complex128(1.7817777974649246e-21+0j)

# Test Original

In [10]:
T_1, T_2, R_1, R_2 = t_periodic(site, state, K, V, V, "original", Import_t=True, t_1_import=t_1_exact, t_2_import=t_2_exact, periodic=periodic, one_cicle=True)

original


In [14]:
np.max(np.abs(R_1))

np.float64(8.673617379884035e-19)

In [12]:
np.max(np.abs(R_2))

np.float64(2.7755575615628914e-17)

# Test Iterative

In [29]:
T_1, T_2, R_1, R_2 = t_periodic(site, state, K, V_xy, V_yx, "linked", Import_t=True, t_1_import=t_1_exact, t_2_import=t_2_exact, periodic=periodic, one_cicle=True)

[[-0.          +0.j]
 [-0.          +0.j]
 [-0.0018724479+0.j]
 [-0.0018724479+0.j]]


In [34]:
np.max(R_1)

np.complex128(4.456596142792869e-19+0j)

In [35]:
np.max(R_2)

np.complex128(4.336808689942018e-19+0j)

In [32]:
np.array_equal(t_1_exact_safe, T_1)

True

In [33]:
np.array_equal(t_2_exact_safe, T_2)

True

In [36]:
R_1.flat[np.argmax(np.abs(single))]

np.complex128(-2.9146288953825136e-06+0j)