In [1]:
import numpy as np
import thermofield_boltz_funcs as bz
import opt_einsum as oe
import scipy.sparse as sp
from quant_rotor.models.sparse.support_ham import build_V_prime_in_p
from quant_rotor.core.dense.de_solve_one_thermal_dense import integration_scheme as integration_scheme_new_dense
from quant_rotor.core.sparse.de_solve_one_thermal_sparse import integration_scheme as integration_scheme_new_sparse
from quant_rotor.core.dense.de_solve_one_thermal import integration_scheme as integration_scheme_old

np.set_printoptions(threshold=np.inf, linewidth=np.inf)

In [2]:
site = 3
state = 3
g = 0.1

In [3]:
beta_d, t_0_dB_d, t_0_sol_d, t_2_max_d  = integration_scheme_new_dense(site, state, g, t_init=0,t_final=10,nof_points=100000)

Done.


In [4]:
beta_s, t_0_dB_s, t_0_sol_s, t_2_max_s  = integration_scheme_new_sparse(site, state, g, t_init=0,t_final=10,nof_points=100000)

Done.


In [5]:
K, V = build_V_prime_in_p(state)
I = np.eye(state)

U, _ = bz.thermofield_change_of_basis(I)

U_sparse = sp.csr_matrix(U)

K_tilda = U_sparse.T @ K @ U_sparse

V_tilda = oe.contract('Mi,Wj,ijab,aN,bV->MWNV', U, U, V.toarray().reshape(state**2, state**2, state**2, state**2), U, U, optimize='optimal')

In [6]:
beta_TF, t_0_dB_TF, t_0_sol_TF, t_2_max_TF  = integration_scheme_old(site, state**2, g, t_init=0,t_final=10,nof_points=100000, import_K_V_TF=True, K_import=K_tilda.toarray(), V_import=V_tilda)

In [7]:
print(np.allclose(beta_s, beta_d))
print(np.allclose(t_0_dB_s, t_0_dB_d))
print(np.allclose(t_0_sol_s, t_0_sol_d))
print(np.allclose(t_2_max_s, t_2_max_d))

True
True
True
True


In [8]:
print(np.allclose(beta_s, beta_TF))
print(np.allclose(t_0_dB_s, t_0_dB_TF))
print(np.allclose(t_0_sol_s, t_0_sol_TF))
print(np.allclose(t_2_max_s, t_2_max_TF))

True
True
True
True


In [9]:
print(np.allclose(beta_d, beta_TF))
print(np.allclose(t_0_dB_d, t_0_dB_TF))
print(np.allclose(t_0_sol_d, t_0_sol_TF))
print(np.allclose(t_2_max_d, t_2_max_TF))

True
True
True
True


# Check the interative step.

In [10]:
comb_flat = np.random.rand(201)

In [11]:
site = 3
state = 3
g = 0.2

In [12]:
K, V = build_V_prime_in_p(state)
I = np.eye(state)

U, _ = bz.thermofield_change_of_basis(I)

U_sparse = sp.csr_matrix(U)

h_full = (U_sparse.T @ K @ U_sparse).toarray()

v_full = oe.contract('Mi,Wj,ijab,aN,bV->MWNV', U, U, V.toarray().reshape(state**2, state**2, state**2, state**2), U, U, optimize='optimal')
v_full = v_full * g

## New.

In [13]:
from quant_rotor.models.dense.t_amplitudes_sub_class_new import QuantumSimulation, TensorData, SimulationParams, PrecalcalculatedTerms

In [14]:
state = state**2
p = state
i = 1
a = p - i

t_a_i_tensor = np.full((a), 0, dtype=complex)
t_ab_ij_tensor = np.full((site, a, a), 0, dtype=complex)

#eigenvalues from h for update
epsilon = np.diag(h_full)

params = SimulationParams(
a=a,
i=i,
p=p,  # These can be the same as `a + i` or chosen independently
site=site,
state=state,
i_method=3,
gap=False,
gap_site=3,
epsilon=epsilon,
periodic=True
)

tensors = TensorData(
t_a_i_tensor=t_a_i_tensor,
t_ab_ij_tensor=t_ab_ij_tensor,
h_full=h_full,
v_full=v_full
)

terms = PrecalcalculatedTerms()
qs_new = QuantumSimulation(params, tensors, terms)

# Initialize T_0 (reference amplitude) as complex zero
t_0 = complex(0)
# Initialize T_ai amplitudes as zeros
single = np.zeros((a), dtype = complex)
double = np.zeros((site, a, a), dtype = complex)

qs_new.terms.h_pp=qs_new.h_term(p, p)
qs_new.terms.h_pa=qs_new.h_term(p, a)
qs_new.terms.h_ip=qs_new.h_term(i, p).reshape(p)
qs_new.terms.V_pppp=qs_new.v_term(p, p, p, p, 0, 1).reshape(p**2, p**2)
qs_new.terms.V_ppaa=qs_new.v_term(p, p, a, a, 0, 1).reshape(p**2, a**2)
qs_new.terms.V_iipp=qs_new.v_term(i, i, p, p, 0, 1).reshape(p, p)
qs_new.terms.V_iiaa=qs_new.v_term(i, i, a, a, 0, 1).reshape(a, a)
qs_new.terms.V_piaa=qs_new.v_term(p, i, a, a, 0, 1).reshape(p, a**2)
qs_new.terms.V_pipp=qs_new.v_term(p, i, p, p, 0, 1).reshape(p, p**2)
qs_new.terms.V_ipap=qs_new.v_term(i, p, a, p, 0, 1).reshape(p, a, p)
qs_new.terms.V_piap=qs_new.v_term(p, i, a, p, 0, 1).reshape(p, a, p)

In [15]:
site, a, p, i = params.site, params.a, params.p, params.i

print(params.a)

dTab_ijdB_sol_new, dTa_idB_sol_new, T_ai_new = comb_flat[:-a-1], comb_flat[-a-1:-1], comb_flat[-1] 
dTab_ijdB_new = dTab_ijdB_sol_new.reshape(site, a, a)
dTa_idB_new = dTa_idB_sol_new.reshape(a)

qs_new.tensors.t_a_i_tensor = dTa_idB_new

for site_1 in range(1, site):
    qs_new.tensors.t_ab_ij_tensor[site_1] = dTab_ijdB_new[site_1]
    print(dTab_ijdB_new[site_1])

# print(dTab_ijdB_sol_new.reshape(site, a, a))

two_max = qs_new.tensors.t_ab_ij_tensor.flat[np.argmax(np.abs(qs_new.tensors.t_ab_ij_tensor))]

qs_new.terms.a_term=qs_new.A_term(a)
qs_new.terms.b_term=qs_new.B_term(i)
qs_new.terms.bb_term=oe.contract("q,s->qs", qs_new.terms.b_term, qs_new.terms.b_term).reshape(p**2)
qs_new.terms.aa_term=oe.contract("ap,bq->abpq", qs_new.terms.a_term, qs_new.terms.a_term).reshape(a**2, p**2)

energy_new = 0

for site_x in range(site):
    energy_new += qs_new.terms.h_ip @ qs_new.terms.b_term

    for site_y in range(site_x + 1, site_x + site):
        if abs(site_x - site_y) == 1 or abs(site_x - site_y) == (site - 1):
            V_iipp = qs_new.terms.V_iipp
            V_iiaa = qs_new.terms.V_iiaa
            T_xy = qs_new.t_term(site_x, site_y)

            # noinspection SpellCheckingInspection
            energy_new +=  np.sum(V_iiaa* (T_xy)) * 0.5
            # noinspection SpellCheckingInspection
            energy_new += (V_iipp @ qs_new.terms.b_term @ qs_new.terms.b_term) * 0.5

single_new = np.zeros((a), dtype = complex)
double_new = np.zeros((site, a, a), dtype = complex)

single_new = qs_new.residual_single()
for y_site in range(1, site):
    double_new[y_site] = qs_new.residual_double_total(y_site)

dTab_ijdB_new = (-1*(double_new))
dTa_idB_new = (-1*(single))
dT_0dB_new = [-1*(energy_new)]

8
[[0.23956056 0.3486029  0.72578327 0.77738293 0.7050013  0.18523676 0.03551828 0.17545684]
 [0.61152948 0.64514398 0.18567169 0.48330691 0.93077901 0.50582887 0.57962414 0.30638527]
 [0.0852091  0.28212068 0.97982108 0.48422004 0.34445982 0.07956906 0.97634799 0.52831085]
 [0.82398567 0.50786643 0.73220831 0.28942882 0.57730073 0.13242844 0.70735393 0.77851583]
 [0.22490016 0.57600895 0.02754314 0.54661966 0.49906792 0.53726261 0.47101555 0.75846167]
 [0.29356593 0.45242713 0.66209565 0.84043384 0.21693403 0.44902373 0.72192499 0.26403698]
 [0.83841066 0.28142306 0.27500363 0.94923028 0.88851767 0.73775989 0.86167877 0.39067838]
 [0.87526447 0.85846121 0.13854478 0.60009706 0.07438977 0.03780161 0.28008489 0.02238435]]
[[0.80364598 0.46276633 0.43502634 0.6997699  0.45288049 0.97692391 0.29575905 0.52229854]
 [0.52039121 0.65684135 0.56103336 0.85753219 0.17012869 0.41855633 0.91912461 0.27633456]
 [0.57358879 0.13165109 0.14450374 0.08742509 0.84593617 0.21423208 0.69596089 0.288714

In [16]:
qs_new.terms.b_term

array([1.        , 0.45293213, 0.812872  , 0.17038018, 0.47397588, 0.6175414 , 0.76303221, 0.80413018, 0.1463206 ])

## Old.

In [17]:
from quant_rotor.models.dense.t_amplitudes_sub_class import QuantumSimulation, TensorData, SimulationParams

In [18]:
site = 3
state = 3
g = 0.2

state = state**2
p = state
i = 1
a = p - i

In [19]:
t_a_i_tensor = np.full((site, a, i), 0, dtype=complex)
t_ab_ij_tensor = np.full((site, site, a, a, i, i), 0, dtype=complex)

#eigenvalues from h for update
epsilon = np.diag(h_full)

params = SimulationParams(
a=a,
i=i,
p=p,  # These can be the same as `a + i` or chosen independently
site=site,
state=state,
i_method=3,
gap=False,
gap_site=3,
epsilon=epsilon,
periodic=True
)

tensors = TensorData(
t_a_i_tensor=t_a_i_tensor,
t_ab_ij_tensor=t_ab_ij_tensor,
h_full=h_full,
v_full=v_full
)

qs_old = QuantumSimulation(params, tensors)

# Initialize T_0 (reference amplitude) as complex zero
t_0 = complex(0)
# Initialize T_ai amplitudes as zeros
single = np.zeros((a,i), dtype = complex)
double = np.zeros((site, a, a, i, i), dtype = complex)

In [20]:
qs_old.h_term(i, p) - qs_new.terms.h_ip

array([[0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [21]:
qs_old.B_term(i, site_x).reshape(p) - qs_new.terms.b_term

array([ 0.        +0.j, -0.45293213+0.j, -0.812872  +0.j, -0.17038018+0.j, -0.47397588+0.j, -0.6175414 +0.j, -0.76303221+0.j, -0.80413018+0.j, -0.1463206 +0.j])

In [22]:
site, a, p, i = params.site, params.a, params.p, params.i

dTab_ijdB_sol_old, dTa_idB_sol_old, T_ai_old = comb_flat[:-a-1], comb_flat[-a-1:-1], comb_flat[-1] 
dTab_ijdB_old = dTab_ijdB_sol_old.reshape(site, a, a, i, i)
dTa_idB_old = dTa_idB_sol_old.reshape(a, i)

# print(dTab_ijdB_sol_old.reshape(site, a, a, i, i).reshape(site, a, a))

# print(np.array_equal(dTab_ijdB_sol_old.reshape(site, a, a), dTab_ijdB_sol_new.reshape(site, a, a)))
# print(np.array_equal(dTa_idB_sol_old.reshape(a), dTa_idB_sol_new.reshape(a)))

qs_old.tensors.t_a_i_tensor[0] = dTa_idB_old

for site_1 in range(1, site):
    qs_old.tensors.t_a_i_tensor[site_1] = qs_old.tensors.t_a_i_tensor[0]
    # print("t_1:", np.array_equal(qs_old.tensors.t_a_i_tensor[0].reshape(a), qs_new.tensors.t_a_i_tensor))
    qs_old.tensors.t_ab_ij_tensor[0, site_1] = dTab_ijdB_old[site_1]
    for site_2 in range(1, site):
        qs_old.tensors.t_ab_ij_tensor[site_2, (site_1 + site_2) % site] = qs_old.tensors.t_ab_ij_tensor[0, site_1]
        # print("t_2:", np.array_equal(qs_old.tensors.t_ab_ij_tensor[site_2, (site_1 + site_2) % site].reshape(a, a), qs_new.tensors.t_ab_ij_tensor[site_1]))
    
print("t_2:", np.array_equal(qs_old.tensors.t_ab_ij_tensor[0].reshape(site, a, a), qs_new.tensors.t_ab_ij_tensor))

two_max = qs_old.tensors.t_ab_ij_tensor.flat[np.argmax(np.abs(qs_old.tensors.t_ab_ij_tensor))]

energy_old = 0

for site_x in range(site):
    energy_old += np.einsum("ip, pi->", qs_old.h_term(i, p), qs_old.B_term(i, site_x))

    for site_y in range(site_x + 1, site_x + site):
        # noinspection SpellCheckingInspection
        energy_old += np.einsum("ijab, abij->", qs_old.v_term(i, i, a, a, site_x, site_y % site), qs_old.t_term(site_x, site_y % site)) * 0.5
        # noinspection SpellCheckingInspection
        energy_old += np.einsum("ijpq, pi, qj->", qs_old.v_term(i, i, p, p, site_x, site_y % site), qs_old.B_term(i, site_x), qs_old.B_term(i, site_y % site)) * 0.5

print("Energy:", np.array_equal(energy_new, energy_old))

single_old = np.zeros((a,i), dtype = complex)
double_old = np.zeros((site, a, a, i, i), dtype = complex)

single_old = qs_old.residual_single(0)

print("Singles:", np.allclose(single_old.reshape(a), single_new))
print(single_old.reshape(a) - single_new)

for y_site in range(1, site):
    double_old[y_site] = qs_old.residual_double_total(0, y_site)
    print("Double:", np.allclose(qs_old.residual_double_total(0, y_site).reshape(a, a), qs_new.residual_double_total(y_site)))
    print("Double:", qs_old.residual_double_total(0, y_site).reshape(a, a) - qs_new.residual_double_total(y_site))

dTa_idB_old = (-1*(single_old))
dTab_ijdB_old = (-1*(double_old))
dT_0dB_old = [-1*(energy_old)]

t_2: True
Energy: True
Singles: True
[-6.93889390e-17+0.j  0.00000000e+00+0.j  0.00000000e+00+0.j  0.00000000e+00+0.j  5.55111512e-17+0.j -2.77555756e-17+0.j  1.11022302e-16+0.j -1.11022302e-16+0.j]
Double: True
Double: [[-1.11022302e-16+0.j -2.22044605e-16+0.j -4.44089210e-16+0.j -2.22044605e-16+0.j -4.44089210e-16+0.j  0.00000000e+00+0.j  2.22044605e-16+0.j  1.11022302e-16+0.j]
 [ 0.00000000e+00+0.j  0.00000000e+00+0.j  5.55111512e-17+0.j -4.44089210e-16+0.j -4.44089210e-16+0.j -2.22044605e-16+0.j -2.22044605e-16+0.j -3.33066907e-16+0.j]
 [-1.66533454e-16+0.j -2.22044605e-16+0.j -1.33226763e-15+0.j  0.00000000e+00+0.j -2.22044605e-16+0.j  8.32667268e-17+0.j  0.00000000e+00+0.j  1.11022302e-16+0.j]
 [-4.44089210e-16+0.j  0.00000000e+00+0.j  0.00000000e+00+0.j -8.88178420e-16+0.j -2.22044605e-16+0.j -2.77555756e-16+0.j -6.66133815e-16+0.j -4.44089210e-16+0.j]
 [-5.55111512e-17+0.j -3.88578059e-16+0.j  2.77555756e-17+0.j -2.22044605e-16+0.j -5.55111512e-17+0.j -2.77555756e-16+0.j  1.110

In [23]:
print(single_new)
double_new

[-0.08871813+0.j -0.30852556+0.j -0.5823696 +0.j -0.98008535+0.j -0.19822275+0.j -0.18347211+0.j -0.30169193+0.j -0.86217347+0.j]


array([[[ 0.00000000e+00+0.j,  0.00000000e+00+0.j,  0.00000000e+00+0.j,  0.00000000e+00+0.j,  0.00000000e+00+0.j,  0.00000000e+00+0.j,  0.00000000e+00+0.j,  0.00000000e+00+0.j],
        [ 0.00000000e+00+0.j,  0.00000000e+00+0.j,  0.00000000e+00+0.j,  0.00000000e+00+0.j,  0.00000000e+00+0.j,  0.00000000e+00+0.j,  0.00000000e+00+0.j,  0.00000000e+00+0.j],
        [ 0.00000000e+00+0.j,  0.00000000e+00+0.j,  0.00000000e+00+0.j,  0.00000000e+00+0.j,  0.00000000e+00+0.j,  0.00000000e+00+0.j,  0.00000000e+00+0.j,  0.00000000e+00+0.j],
        [ 0.00000000e+00+0.j,  0.00000000e+00+0.j,  0.00000000e+00+0.j,  0.00000000e+00+0.j,  0.00000000e+00+0.j,  0.00000000e+00+0.j,  0.00000000e+00+0.j,  0.00000000e+00+0.j],
        [ 0.00000000e+00+0.j,  0.00000000e+00+0.j,  0.00000000e+00+0.j,  0.00000000e+00+0.j,  0.00000000e+00+0.j,  0.00000000e+00+0.j,  0.00000000e+00+0.j,  0.00000000e+00+0.j],
        [ 0.00000000e+00+0.j,  0.00000000e+00+0.j,  0.00000000e+00+0.j,  0.00000000e+00+0.j,  0.00000000e+00+0

In [24]:
print(single_old.reshape(a))
double_old.reshape(site, a, a)

[-0.08871813+0.j -0.30852556+0.j -0.5823696 +0.j -0.98008535+0.j -0.19822275+0.j -0.18347211+0.j -0.30169193+0.j -0.86217347+0.j]


array([[[ 0.00000000e+00+0.j,  0.00000000e+00+0.j,  0.00000000e+00+0.j,  0.00000000e+00+0.j,  0.00000000e+00+0.j,  0.00000000e+00+0.j,  0.00000000e+00+0.j,  0.00000000e+00+0.j],
        [ 0.00000000e+00+0.j,  0.00000000e+00+0.j,  0.00000000e+00+0.j,  0.00000000e+00+0.j,  0.00000000e+00+0.j,  0.00000000e+00+0.j,  0.00000000e+00+0.j,  0.00000000e+00+0.j],
        [ 0.00000000e+00+0.j,  0.00000000e+00+0.j,  0.00000000e+00+0.j,  0.00000000e+00+0.j,  0.00000000e+00+0.j,  0.00000000e+00+0.j,  0.00000000e+00+0.j,  0.00000000e+00+0.j],
        [ 0.00000000e+00+0.j,  0.00000000e+00+0.j,  0.00000000e+00+0.j,  0.00000000e+00+0.j,  0.00000000e+00+0.j,  0.00000000e+00+0.j,  0.00000000e+00+0.j,  0.00000000e+00+0.j],
        [ 0.00000000e+00+0.j,  0.00000000e+00+0.j,  0.00000000e+00+0.j,  0.00000000e+00+0.j,  0.00000000e+00+0.j,  0.00000000e+00+0.j,  0.00000000e+00+0.j,  0.00000000e+00+0.j],
        [ 0.00000000e+00+0.j,  0.00000000e+00+0.j,  0.00000000e+00+0.j,  0.00000000e+00+0.j,  0.00000000e+00+0

In [25]:
print(np.array_equal(dTab_ijdB_new, dTa_idB_old))
print(np.array_equal(dTab_ijdB_new, dTab_ijdB_old))
print(np.array_equal(dT_0dB_new, dT_0dB_old))

False
False
True
