In [2]:
import numpy as np
from scipy.sparse.linalg import eigsh
from itertools import product
from collections import defaultdict
import time
import csv
import functions as func
import hamiltonianGenerator as hG
import pandas as pd

# Generating the possible combinations of states

In [ ]:
sites = 3
states = 2

In [11]:
matrix = np.zeros((8,8))
matrix[1,2] = 1
matrix

array([[0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.]])

In [12]:
for p in range(0,8):
    for q in range(0,8):
        for r in range(0,8):
            matrix[r,q] = p + q*10 + r*100

matrix

array([[  7.,  17.,  27.,  37.,  47.,  57.,  67.,  77.],
       [107., 117., 127., 137., 147., 157., 167., 177.],
       [207., 217., 227., 237., 247., 257., 267., 277.],
       [307., 317., 327., 337., 347., 357., 367., 377.],
       [407., 417., 427., 437., 447., 457., 467., 477.],
       [507., 517., 527., 537., 547., 557., 567., 577.],
       [607., 617., 627., 637., 647., 657., 667., 677.],
       [707., 717., 727., 737., 747., 757., 767., 777.]])

In [15]:
def generate_matrix(site, state):
    states = ["".join(map(str, digits)) for digits in product(range(state), repeat=site)]
    matrix = []

    for row in states:
        row_entries = [f"{row}|{col}" for col in states]
        matrix.append(row_entries)

    return matrix


def print_matrix(matrix):
    for row in matrix:
        print(" ".join(row))

In [14]:
# Example usage
site = 3
state = 2
matrix = generate_matrix(site, state)
print_matrix(matrix)


000|000 000|001 000|010 000|011 000|100 000|101 000|110 000|111
001|000 001|001 001|010 001|011 001|100 001|101 001|110 001|111
010|000 010|001 010|010 010|011 010|100 010|101 010|110 010|111
011|000 011|001 011|010 011|011 011|100 011|101 011|110 011|111
100|000 100|001 100|010 100|011 100|100 100|101 100|110 100|111
101|000 101|001 101|010 101|011 101|100 101|101 101|110 101|111
110|000 110|001 110|010 110|011 110|100 110|101 110|110 110|111
111|000 111|001 111|010 111|011 111|100 111|101 111|110 111|111


# Converting Sheers matrix from m to p and saving it

## Free one body system. (Work in progress)

In [ ]:

# # Original matrix A
# A = np.array([
#     [1, 2, 3, 4],
#     [2, 5, 6, 7],
#     [3, 6, 8, 9],
#     [4, 7, 9, 10]
# ])
# print(A)
# # Index map: new_index[i] = index of row i in the new basis
# index_map = [0, 3, 1, 2]  # Example: remap row/col 1 → 3, 2 → 1, 3 → 2

# # Permute rows and columns accordingly
# A_new = A[np.ix_(index_map, index_map)]
# A_new = A_new.T[np.ix_(index_map, index_map)]

# print(A_new)

# P = np.eye(len(index_map))[index_map]
# A_new2 = P.T @ A @ P

# print(A_new2)

[[ 1  2  3  4]
 [ 2  5  6  7]
 [ 3  6  8  9]
 [ 4  7  9 10]]
[[ 1  3  4  2]
 [ 3  8  9  6]
 [ 4  9 10  7]
 [ 2  6  7  5]]
[[ 1.  3.  4.  2.]
 [ 3.  8.  9.  6.]
 [ 4.  9. 10.  7.]
 [ 2.  6.  7.  5.]]


In [6]:
def free_one_body(max_m: int)-> np.array:

    p_max = 2*max_m + 1
    p_vect = np.zeros(p_max)

    m = 0

    for i in range(1, max_m+1):

        p_vect[i + m] = i**2
        p_vect[i + 1 + m] = (-i)**2
        m+=1
    
    print(p_vect)

    return  np.diag(p_vect)

K_new = free_one_body(5)

K_new

[ 0.  1.  1.  4.  4.  9.  9. 16. 16. 25. 25.]


array([[ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  4.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  4.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  9.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  9.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0., 16.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0., 16.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0., 25.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0., 25.]])

In [78]:
df = pd.read_csv(
    "/Users/gilfrim/Desktop/QuantumChemistryCoop/Main-CC-files/matrix_elements_K.csv",
    skiprows=1, header=0
)

# Clean column names
df.columns = [col.strip() for col in df.columns]

# Convert columns safely
df["m1"] = df["m1"].astype(int)
df["m2"] = df["m2"].astype(int)
df["<m1|K|m2>"] = df["<m1|K|m2>"].astype(float)

# Matrix size and init
size = max(df["m1"].max(), df["m2"].max()) + 1
K = np.zeros((size, size))

m = (size - 1) / 2

# Fill matrix
for _, row in df.iterrows():

    i = int(row["m1"])
    j = int(row["m2"])
    val = float(row["<m1|K|m2>"])
    K[i, j] = val
    K[j, i] = val

    
# Show matrix
print(pd.DataFrame(K))
print(pd.DataFrame(K_new))

      0     1    2    3    4    5    6    7    8     9     10
0   25.0   0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   0.0   0.0
1    0.0  16.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   0.0   0.0
2    0.0   0.0  9.0  0.0  0.0  0.0  0.0  0.0  0.0   0.0   0.0
3    0.0   0.0  0.0  4.0  0.0  0.0  0.0  0.0  0.0   0.0   0.0
4    0.0   0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0   0.0   0.0
5    0.0   0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   0.0   0.0
6    0.0   0.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0   0.0   0.0
7    0.0   0.0  0.0  0.0  0.0  0.0  0.0  4.0  0.0   0.0   0.0
8    0.0   0.0  0.0  0.0  0.0  0.0  0.0  0.0  9.0   0.0   0.0
9    0.0   0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  16.0   0.0
10   0.0   0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   0.0  25.0
     0    1    2    3    4    5    6     7     8     9     10
0   0.0  0.0  0.0  0.0  0.0  0.0  0.0   0.0   0.0   0.0   0.0
1   0.0  1.0  0.0  0.0  0.0  0.0  0.0   0.0   0.0   0.0   0.0
2   0.0  0.0  1.0  0.0  0.0  0.0  0.0   0.0   0.0   0.0   0.0
3   0.0 

In [ ]:
# p_vect = np.zeros(11)
p_vect = np.array([0,  -1, 1,  -2, 2,  -3, 3,  -4, 4,  -5, 5])
m=0
vec1 = np.zeros(11)

for i in range(11):
    vec1[i] = int(func.m_to_p(p_vect[i]))

print(p_vect)
print(vec1)

[ 0 -1  1 -2  2 -3  3 -4  4 -5  5]
[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]


In [97]:
m = 3
dim = 2*m +1
K_to_see = np.zeros((dim, dim))
p_vect = np.zeros(dim)

for i in range(1, m+1):

        p_vect[i + m] = i**2
        p_vect[i + 1 + m] = (-i)**2
        m+=1

for i in range(dim):
    for j in range(m):
          K_to_see[i,j] = 5+5

IndexError: index 7 is out of bounds for axis 0 with size 7

## Free one body system. (Final Function)

In [28]:

# # Original matrix A
# A = np.array([
#     [1, 2, 3, 4],
#     [2, 5, 6, 7],
#     [3, 6, 8, 9],
#     [4, 7, 9, 10]
# ])
# print(A)
# # Index map: new_index[i] = index of row i in the new basis
# index_map = [0, 3, 1, 2]  # Example: remap row/col 1 → 3, 2 → 1, 3 → 2

# # Permute rows and columns accordingly
# A_new = A[np.ix_(index_map, index_map)]
# A_new = A_new.T[np.ix_(index_map, index_map)]

# print(A_new)

# P = np.eye(len(index_map))[index_map]
# A_new2 = P.T @ A @ P

# print(A_new2)

In [ ]:
def create_index_map(dim: int)->np.array:

    index_map = np.arange(-dim,dim+1)

    vectorised_m_to_p = np.vectorize(func.m_to_p)
    index_map = vectorised_m_to_p(index_map)

    return index_map

print(create_index_map(9))

def basis_m_to_p_matrix_conversion(matrix: np.ndarray)->np.ndarray:

    dim = matrix.shape[0]
    index_map = create_index_map((dim-1)//2)

    matrix = matrix[np.ix_(index_map, index_map)]
    matrix = matrix.T[np.ix_(index_map, index_map)]

    return matrix

A = np.array([
    [1, 2, 3, 4, 1],
    [2, 5, 6, 7, 1],
    [3, 6, 8, 9, 1],
    [4, 7, 9, 10, 1],
    [5, 8, 10, 11, 11]
])

print(basis_m_to_p_matrix_conversion(A))

[17 15 13 11  9  7  5  3  1  0  2  4  6  8 10 12 14 16 18]
[[ 8  6  9  3 10]
 [ 6  5  7  2  8]
 [ 9  7 10  4 11]
 [ 3  2  4  1  5]
 [ 1  1  1  1 11]]


## Coplaner two body system

### Learning einsum

1. Inner product of vectors

'i,i->': sum over index i (vector inner product)

In [81]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

np.dot(a, b)         # → 32
np.einsum('i,i->', a, b)  # → 32

32

2. Matrix multiplication

'ik,kj->ij': sum over index k (standard matrix multiplication)

In [82]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[2, 0], [1, 2]])

np.matmul(A, B)
np.einsum('ik,kj->ij', A, B)

array([[ 4,  4],
       [10,  8]])

3. Trace of a matrix

'ii->': sum diagonal elements (same index repeated = sum)

In [83]:
a = np.array([1, 2])
b = np.array([3, 4, 5])

np.einsum('i,j->ij', a, b)
# Result: 2x3 matrix of a[i] * b[j]

array([[ 3,  4,  5],
       [ 6,  8, 10]])

4. Tensor contraction

Contracts the last index of T with w (like applying weights)

In [84]:
T = np.random.rand(2, 3, 4)
w = np.random.rand(4)

np.einsum('ijk,k->ij', T, w)

array([[0.93882073, 0.96995704, 1.08514116],
       [0.734377  , 0.76955526, 0.76790332]])

5. Outer product

In [85]:
a = np.array([1, 2])
b = np.array([3, 4, 5])

np.einsum('i,j->ij', a, b)
# Result: 2x3 matrix of a[i] * b[j]

array([[ 3,  4,  5],
       [ 6,  8, 10]])

###

$$
V = 0.75 \sum_{m_1, m_2} \left( |m_1, m_2\rangle \langle m_1 + 1, m_2 + 1| + |m_1, m_2\rangle \langle m_1 - 1, m_2 - 1| \right) \\
\quad -\ 0.25 \sum_{m_1, m_2} \left( |m_1, m_2\rangle \langle m_1 - 1, m_2 + 1| + |m_1, m_2\rangle \langle m_1 + 1, m_2 - 1| \right)
$$

In [86]:
import numpy as np
import hamiltonianGenerator as hg
import pandas as pd

np.set_printoptions(suppress = True, linewidth = 10000, threshold = 1000000, precision = 6)

# Script for diagonalizing the Hamiltonian for 2 dipolar rotors oriented along the x direction. 
# m_max = 5 is sufficient for convergence when studying ground state properties. 
m_max = 5
d = 2*m_max + 1
K_1 = np.zeros((d,d))
for i in range(d):
    K_1[i,i] = hg.free_one_body(i, i, m_max)

K_2 = np.kron(K_1, np.eye(d)) + np.kron(np.eye(d), K_1)

# Interaction for a coplanar chain is proportional to (yiyj + 2xixj)/r^3. If sites are not coplanar, 
# the interaction will be some other linear combination of xixj, yiyj, (xiyj + xjyi). The coefficients 
# will, in general, depend on the angle as well as the length of the vector connecting the sites. 
V2 = np.zeros((d**2, d**2))

for i in range(d):
    for j in range(d):
        for k in range(d):
            for l in range(d):
                V2[i*d + j,k*d + l] = hg.interaction_yiyj(i, j, k, l) + 2*hg.interaction_xixj(i, j, k, l)
'''
num_pts = 20
E0_array = np.zeros((num_pts, 2))
for i in range(num_pts):
    g = (i+1.0)/num_pts
    H_2 = K_2 + g * V_2
    evals, evecs = np.linalg.eigh(H_2)
    E0 = evals[0]
    E0_array[i, 0] = g
    E0_array[i, 1] = E0

np.savetxt("E0_N2_ED.csv", E0_array, delimiter=",", header="g, E0")'''


print(pd.DataFrame(V2))

     0    1    2    3    4    5    6    7    8    9    ...  111  112  113  \
0    0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   
1    0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   
2    0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   
3    0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   
4    0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   
..   ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...   
116  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   
117  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   
118  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   
119  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   
120  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   

     114  115  116  117  118  119  120  
0    0.0  0.0  0.0  0.0  0.0  0.0 